"use client";
import { useState } from "react";
import { Button, type DataTableColumn } from "@/components/ui";
import { LegalDataPage, type LegalTab } from "../shared/legal-data-page";
import { LegalExtractionDrawer, LegalUnavailableFormDrawer, type LegalFormField } from "../shared/legal-ui";
type CaseRow = { readonly id: string };
const columns: readonly DataTableColumn<CaseRow>[] = ["Nomor Kasus", "Judul", "Jenis", "Pihak Lawan", "Proyek Terkait", "Penanggung Jawab", "Tanggal Dibuka", "Tahap", "Risiko", "Tenggat Berikutnya", "Status"].map((header) => ({ header, key: header, render: () => header === "Tahap" || header === "Risiko" || header === "Status" ? "Belum Dinilai" : "—" }));
const fields: readonly LegalFormField[] = [{ label: "Judul", name: "title", required: true }, { label: "Jenis", name: "type", required: true }, { label: "Pihak Lawan", name: "counterparty" }, { label: "Proyek Terkait", name: "project", relation: true, sourceReady: false }, { label: "Penanggung Jawab", name: "owner", required: true, relation: true, sourceReady: false }, { label: "Tanggal Dibuka", name: "opened", type: "date", required: true }, { label: "Deskripsi", name: "description", type: "textarea", required: true }, { label: "Risiko", name: "risk" }, { label: "Tenggat Berikutnya", name: "deadline", type: "date" }, { label: "Dokumen", name: "document", relation: true, sourceReady: false }, { label: "Bukti", name: "evidence" }, { label: "Klasifikasi", name: "classification", required: true }];
export function LegalCasesPage({ workspaceKey }: Readonly<{ workspaceKey?: string }>) { const [open, setOpen] = useState(false); const [extract, setExtract] = useState(false); const tabs: readonly LegalTab<CaseRow>[] = ["Semua", "Aktif", "Perlu Tindakan", "Selesai", "Riwayat"].map((label) => ({ id: label, label, title: label === "Semua" ? "Sengketa & Klaim" : `Sengketa & Klaim — ${label}`, description: "Tahap perkara dan risiko menunggu sumber legal resmi; estimasi legal dipisahkan dari aktual Keuangan.", caption: `Daftar kasus ${label}`, columns, emptyDescription: "Data sengketa dan klaim belum tersedia.", actions: label === "Semua" ? <><Button onClick={() => setOpen(true)}>Tambah Kasus</Button><Button onClick={() => setExtract(true)} variant="secondary">Telaah Dokumen</Button></> : undefined, rows: [], children: label === "Semua" ? <><LegalUnavailableFormDrawer description="Form kasus siap digunakan setelah sumber penyimpanan resmi tersedia." fields={fields} onClose={() => setOpen(false)} open={open} submitLabel="Simpan Kasus" title="Tambah Kasus" /><LegalExtractionDrawer onClose={() => setExtract(false)} open={extract} /></> : undefined })); return <LegalDataPage description="Pantau sengketa dan klaim dengan tampilan kesiapan tanpa menetapkan tahapan perkara." tabs={tabs} title="Sengketa & Klaim" workspaceKey={workspaceKey} />; }
