/**
 * Executive Data Requirement Registry
 * ALOS MVP-2 Stage 3A — Executive Command Center (Pusat Kendali Eksekutif)
 * 
 * Mendefinisikan kontrak metadata bisnis, semantik periode, sumber target/aktual/perkiraan,
 * wewenang kepemilikan, dan aturan kesegaran data untuk setiap komponen eksekutif.
 */

export interface ExecutiveDataRequirement {
  readonly id: string;
  readonly label: string;
  readonly business_purpose: string;
  readonly metric_or_entity: string;
  readonly scope: "COMPANY" | "DIVISION" | "PROJECT" | "WORKFLOW";
  readonly period_semantics: "ANNUAL" | "QUARTERLY" | "MONTHLY" | "WEEKLY" | "DAILY" | "REALTIME" | "CUSTOM";
  readonly target_source: string | null;
  readonly actual_source: string | null;
  readonly forecast_source: string | null;
  readonly owner_role: string;
  readonly owner_domain: "executive" | "sales" | "property" | "finance" | "legal" | "hr" | "it" | "strategy";
  readonly evidence_requirement: readonly string[];
  readonly verification_requirement: string;
  readonly freshness_rule: "REALTIME" | "HOURLY" | "DAILY" | "WEEKLY" | "MONTHLY";
  readonly readiness_source: "CONNECTED" | "NOT_CONNECTED" | "PARTIAL";
  readonly drilldown_href: string;
}

export const EXECUTIVE_DATA_REQUIREMENTS: readonly ExecutiveDataRequirement[] = [
  {
    id: "executive.headline.revenue",
    label: "Pendapatan Korporat",
    business_purpose: "Memantau realisasi perolehan pendapatan bruto perusahaan dibandingkan target RKAP berjalan.",
    metric_or_entity: "HEADLINE-REVENUE",
    scope: "COMPANY",
    period_semantics: "ANNUAL",
    target_source: "strategy.business_target",
    actual_source: "finance.verified_revenue_ledger",
    forecast_source: "finance.revenue_projection",
    owner_role: "WORKSPACE_LEAD",
    owner_domain: "finance",
    evidence_requirement: ["rekening_koran", "bukti_penerimaan_kas", "faktur_penjualan"],
    verification_requirement: "Rekonsiliasi bank dan approval Finance Lead",
    freshness_rule: "DAILY",
    readiness_source: "NOT_CONNECTED",
    drilldown_href: "/workspace/finance",
  },
  {
    id: "executive.headline.closing",
    label: "Penjualan / Closing Unit",
    business_purpose: "Memantau volume akad dan closing unit properti yang telah terverifikasi terhadap kuota penjualan tahunan.",
    metric_or_entity: "HEADLINE-CLOSING",
    scope: "COMPANY",
    period_semantics: "ANNUAL",
    target_source: "strategy.business_target",
    actual_source: "sales.verified_closing",
    forecast_source: "sales.pipeline_forecast",
    owner_role: "WORKSPACE_LEAD",
    owner_domain: "sales",
    evidence_requirement: ["spk_signed", "bukti_booking_fee", "akta_jual_beli"],
    verification_requirement: "Verifikasi dokumen akad notaris & konfirmasi booking fee",
    freshness_rule: "DAILY",
    readiness_source: "NOT_CONNECTED",
    drilldown_href: "/workspace/sales",
  },
  {
    id: "executive.headline.liquidity",
    label: "Kas & Likuiditas",
    business_purpose: "Menjaga solvabilitas dan ketersediaan dana operasional jangka pendek di seluruh rekening bank perusahaan.",
    metric_or_entity: "HEADLINE-LIQUIDITY",
    scope: "COMPANY",
    period_semantics: "DAILY",
    target_source: "finance.operating_reserve_target",
    actual_source: "finance.bank_balances_reconciled",
    forecast_source: "finance.cashflow_forecast",
    owner_role: "WORKSPACE_LEAD",
    owner_domain: "finance",
    evidence_requirement: ["rekening_koran_resmi", "berita_acara_kas_opname"],
    verification_requirement: "Rekonsiliasi harian seluruh rekening giro aktif",
    freshness_rule: "DAILY",
    readiness_source: "NOT_CONNECTED",
    drilldown_href: "/workspace/finance",
  },
  {
    id: "executive.headline.delivery",
    label: "Progres Proyek Agregat",
    business_purpose: "Mengukur deviasi rata-rata kemajuan fisik proyek konstruksi terhadap kurva S rencana.",
    metric_or_entity: "HEADLINE-DELIVERY",
    scope: "COMPANY",
    period_semantics: "WEEKLY",
    target_source: "property.master_scurve_planned",
    actual_source: "property.opname_progress_verified",
    forecast_source: "property.estimated_completion_date",
    owner_role: "WORKSPACE_LEAD",
    owner_domain: "property",
    evidence_requirement: ["laporan_mingguan_konsultan", "geotag_photos", "berita_acara_opname"],
    verification_requirement: "Validasi geotag site inspection dan approval Project Lead",
    freshness_rule: "WEEKLY",
    readiness_source: "PARTIAL",
    drilldown_href: "/workspace/executive/projects",
  },
  {
    id: "executive.headline.decisions",
    label: "Keputusan Menunggu",
    business_purpose: "Memastikan antrean persetujuan dokumen material dan rilis kapabilitas agen selesai tepat waktu sesuai tata kelola.",
    metric_or_entity: "HEADLINE-DECISIONS",
    scope: "COMPANY",
    period_semantics: "REALTIME",
    target_source: "executive.approval_sla_target",
    actual_source: "executive.pending_approvals_count",
    forecast_source: null,
    owner_role: "EXECUTIVE",
    owner_domain: "executive",
    evidence_requirement: ["dokumen_pengajuan", "analisis_dampak", "lembar_rekomendasi"],
    verification_requirement: "Persetujuan bertanda tangan digital Direktur Utama",
    freshness_rule: "REALTIME",
    readiness_source: "PARTIAL",
    drilldown_href: "/workspace/executive/approvals",
  },
  {
    id: "executive.headline.risk",
    label: "Risiko & Peringatan Dini",
    business_purpose: "Mengidentifikasi deviasi proyek kritis, keterlambatan keputusan, dan indikator kegagalan sebelum eskalasi.",
    metric_or_entity: "HEADLINE-RISK",
    scope: "COMPANY",
    period_semantics: "REALTIME",
    target_source: "executive.zero_critical_risk_target",
    actual_source: "executive.early_warning_signals",
    forecast_source: null,
    owner_role: "EXECUTIVE",
    owner_domain: "executive",
    evidence_requirement: ["laporan_penyimpangan", "audit_log_keterlambatan"],
    verification_requirement: "Validasi komite risiko & monitoring berkala",
    freshness_rule: "REALTIME",
    readiness_source: "PARTIAL",
    drilldown_href: "/workspace/executive/approvals",
  },
  {
    id: "executive.corporate.targets",
    label: "Pencapaian Target Perusahaan",
    business_purpose: "Menampilkan status eksekusi target tahunan (Renstra & RKAP) bersumber dari Backend Strategy API Stage 2.",
    metric_or_entity: "CORPORATE-TARGETS-REGISTRY",
    scope: "COMPANY",
    period_semantics: "ANNUAL",
    target_source: "strategy.targets_backend_api",
    actual_source: "strategy.target_observations_actual",
    forecast_source: "strategy.target_observations_forecast",
    owner_role: "EXECUTIVE",
    owner_domain: "strategy",
    evidence_requirement: ["sk_direksi_rkap", "dokumen_target_resmi"],
    verification_requirement: "Pemeriksaan integritas kontrak Stage 2 Strategy",
    freshness_rule: "HOURLY",
    readiness_source: "CONNECTED",
    drilldown_href: "/workspace/executive/strategy",
  },
  {
    id: "executive.domain.sales",
    label: "Kinerja Penjualan & Komersial",
    business_purpose: "Menyajikan ringkasan konversi alur penjualan dari prospek hingga akad kredit kepemilikan rumah.",
    metric_or_entity: "SALES-COMMERCIAL-FUNNEL",
    scope: "DIVISION",
    period_semantics: "MONTHLY",
    target_source: "strategy.sales_targets",
    actual_source: "sales.crm_pipeline_state",
    forecast_source: "sales.projected_akad",
    owner_role: "WORKSPACE_LEAD",
    owner_domain: "sales",
    evidence_requirement: ["rekap_leads", "spk_terdaftar", "surat_sp3k_bank"],
    verification_requirement: "Verifikasi berkas akad dan konfirmasi tim legal-sales",
    freshness_rule: "DAILY",
    readiness_source: "NOT_CONNECTED",
    drilldown_href: "/workspace/sales",
  },
  {
    id: "executive.domain.finance",
    label: "Kondisi Keuangan",
    business_purpose: "Menyajikan ringkasan arus kas masuk/keluar, realisasi anggaran, dan kepatuhan perpajakan.",
    metric_or_entity: "FINANCIAL-HEALTH-OVERVIEW",
    scope: "DIVISION",
    period_semantics: "MONTHLY",
    target_source: "strategy.budget_plan",
    actual_source: "finance.gl_summary_actual",
    forecast_source: "finance.burn_rate_forecast",
    owner_role: "WORKSPACE_LEAD",
    owner_domain: "finance",
    evidence_requirement: ["laporan_laba_rugi", "rekap_rekening_koran", "bukti_setor_pajak"],
    verification_requirement: "Rekonsiliasi berkas akuntansi bulanan & audit internal",
    freshness_rule: "DAILY",
    readiness_source: "NOT_CONNECTED",
    drilldown_href: "/workspace/finance",
  },
  {
    id: "executive.domain.property",
    label: "Proyek & Konstruksi",
    business_purpose: "Menyajikan ringkasan pelaksanaan fisik klaster perumahan, pencapaian 7 hold points, dan keselamatan kerja.",
    metric_or_entity: "CONSTRUCTION-PORTFOLIO-SUMMARY",
    scope: "DIVISION",
    period_semantics: "WEEKLY",
    target_source: "strategy.property_schedule",
    actual_source: "property.field_inspection_log",
    forecast_source: "property.pho_forecast",
    owner_role: "WORKSPACE_LEAD",
    owner_domain: "property",
    evidence_requirement: ["laporan_k3", "checklist_7_hold_points", "foto_opname"],
    verification_requirement: "Verifikasi pengawas lapangan dan persetujuan Project Manager",
    freshness_rule: "DAILY",
    readiness_source: "PARTIAL",
    drilldown_href: "/workspace/executive/projects",
  },
  {
    id: "executive.domain.legal",
    label: "Legal, Perizinan & KPR",
    business_purpose: "Menyajikan status legalitas lahan, sertifikat pecahan, izin PBG/SLF, dan penyelesaian berkas KPR.",
    metric_or_entity: "LEGAL-PERMITS-COMPLIANCE",
    scope: "DIVISION",
    period_semantics: "MONTHLY",
    target_source: "strategy.legal_milestones",
    actual_source: "legal.document_registry_verified",
    forecast_source: "legal.permit_timeline_forecast",
    owner_role: "WORKSPACE_LEAD",
    owner_domain: "legal",
    evidence_requirement: ["sertifikat_hgb_induk", "sk_pbg", "draft_pks_bank"],
    verification_requirement: "Verifikasi keaslian dokumen BPN/Dinas Penanaman Modal",
    freshness_rule: "WEEKLY",
    readiness_source: "NOT_CONNECTED",
    drilldown_href: "/workspace/legal",
  },
  {
    id: "executive.domain.hr",
    label: "SDM & Organisasi",
    business_purpose: "Menyajikan komposisi karyawan aktif, tingkat absensi, pemisahan tugas (SoD), dan kedisiplinan organisasi.",
    metric_or_entity: "HR-PEOPLE-ORGANIZATION",
    scope: "DIVISION",
    period_semantics: "MONTHLY",
    target_source: "strategy.workforce_plan",
    actual_source: "hr.hris_employee_records",
    forecast_source: null,
    owner_role: "WORKSPACE_LEAD",
    owner_domain: "hr",
    evidence_requirement: ["rekap_absensi_biometrik", "matriks_sod", "sk_pengangkatan"],
    verification_requirement: "Validasi absensi bulanan dan audit hak akses IT",
    freshness_rule: "DAILY",
    readiness_source: "NOT_CONNECTED",
    drilldown_href: "/workspace/hr",
  },
  {
    id: "executive.domain.it",
    label: "Teknologi & Platform ALOS",
    business_purpose: "Memantau ketersediaan sistem ALOS, integritas backend, tata kelola kontrol agen GENESIS, dan kepatuhan anggaran AI.",
    metric_or_entity: "IT-PLATFORM-HEALTH",
    scope: "DIVISION",
    period_semantics: "REALTIME",
    target_source: "strategy.sla_uptime_target",
    actual_source: "it.observability_telemetry",
    forecast_source: "it.ai_token_budget_projection",
    owner_role: "WORKSPACE_LEAD",
    owner_domain: "it",
    evidence_requirement: ["otel_collector_logs", "healthcheck_probes", "token_usage_records"],
    verification_requirement: "Pemeriksaan otomatis continuous monitoring & verifikasi IT Lead",
    freshness_rule: "REALTIME",
    readiness_source: "NOT_CONNECTED",
    drilldown_href: "/workspace/it",
  },
  {
    id: "executive.division.health",
    label: "Status Operasional Divisi",
    business_purpose: "Memberikan matriks status operasional 6 divisi tanpa skor buatan, mencakup dokumen dan beban alur kerja aktif.",
    metric_or_entity: "DIVISION-OPERATIONAL-STATE",
    scope: "COMPANY",
    period_semantics: "REALTIME",
    target_source: "executive.division_readiness_standard",
    actual_source: "executive.snapshot_divisions",
    forecast_source: null,
    owner_role: "EXECUTIVE",
    owner_domain: "executive",
    evidence_requirement: ["daftar_alur_kerja_aktif", "rekap_dokumen_divisi"],
    verification_requirement: "Agregasi berkala dari masing-masing workspace divisi",
    freshness_rule: "HOURLY",
    readiness_source: "PARTIAL",
    drilldown_href: "/workspace/executive/divisions",
  },
  {
    id: "executive.genesis.analysis",
    label: "Analisis Advisory GENESIS",
    business_purpose: "Menampilkan rekomendasi dan temuan risiko dari agen pengawas GENESIS secara tenang tanpa klaim wewenang otomatis.",
    metric_or_entity: "GENESIS-ADVISORY-SYNTHESIS",
    scope: "COMPANY",
    period_semantics: "REALTIME",
    target_source: "it.genesis_supervision_policy",
    actual_source: "genesis.advisory_findings_backend",
    forecast_source: null,
    owner_role: "EXECUTIVE",
    owner_domain: "executive",
    evidence_requirement: ["log_analisis_agen", "lineage_korelasi_data"],
    verification_requirement: "Tinjauan penasihat manusia sebelum eksekusi",
    freshness_rule: "HOURLY",
    readiness_source: "NOT_CONNECTED",
    drilldown_href: "/workspace/executive/ara",
  },
  {
    id: "executive.governance.cadence",
    label: "Ritme Pelaporan & Tata Kelola",
    business_purpose: "Menyediakan jadwal dan disiplin tinjauan operasional berkala untuk Direktur dan pimpinan lintas divisi.",
    metric_or_entity: "GOVERNANCE-RHYTHM-CALENDAR",
    scope: "COMPANY",
    period_semantics: "CUSTOM",
    target_source: "executive.corporate_governance_calendar",
    actual_source: "executive.governance_executions",
    forecast_source: null,
    owner_role: "EXECUTIVE",
    owner_domain: "executive",
    evidence_requirement: ["notulen_rapat_direksi", "risalah_briefing_pagi"],
    verification_requirement: "Dokumentasi risalah rapat tertanda tangan",
    freshness_rule: "DAILY",
    readiness_source: "CONNECTED",
    drilldown_href: "/workspace/executive/reports",
  },
] as const;
