"use client";
import { useState } from "react";
import { Button, type DataTableColumn } from "@/components/ui";
import { LegalDataPage, type LegalTab } from "../shared/legal-data-page";
import { LegalExtractionDrawer, LegalUnavailableFormDrawer, type LegalFormField } from "../shared/legal-ui";

type ContractRow = { readonly id: string };
const columns: readonly DataTableColumn<ContractRow>[] = ["Nomor Kontrak", "Nama Kontrak", "Pihak", "Jenis", "Proyek / Divisi", "Tanggal Efektif", "Tanggal Akhir", "Status Legal", "Persetujuan", "Penanggung Jawab", "Review Terakhir"].map((header) => ({ header, key: header, render: () => header.includes("Status") || header === "Persetujuan" ? "Belum Dinilai" : "—" }));
const fields: readonly LegalFormField[] = [{ label: "Nama Kontrak", name: "name", required: true }, { label: "Jenis", name: "type", required: true }, { label: "Nomor Kontrak", name: "number" }, { label: "Pihak", name: "party", required: true, relation: true, sourceReady: false }, { label: "Divisi / Ruang Kerja", name: "workspace", required: true, relation: true, sourceReady: false }, { label: "Proyek", name: "project", relation: true, sourceReady: false }, { label: "Penanggung Jawab", name: "owner", required: true, relation: true, sourceReady: false }, { label: "Tanggal Efektif", name: "effective", type: "date", required: true }, { label: "Tanggal Akhir", name: "end", type: "date" }, { label: "Jenis Perpanjangan", name: "renewal" }, { label: "Materialitas", name: "materiality", required: true }, { label: "Klasifikasi", name: "classification", required: true }, { label: "Deskripsi", name: "description", type: "textarea" }, { label: "Dokumen Sumber", name: "document", required: true, relation: true, sourceReady: false }, { label: "Bukti", name: "evidence" }];
export function LegalContractsPage({ workspaceKey }: Readonly<{ workspaceKey?: string }>) { const [open, setOpen] = useState(false); const [extract, setExtract] = useState(false); const action = <><Button onClick={() => setOpen(true)}>Tambah Kontrak</Button><Button onClick={() => setExtract(true)} variant="secondary">Telaah Dokumen</Button></>; const tabs: readonly LegalTab<ContractRow>[] = ["Semua", "Draf", "Dalam Review", "Menunggu Persetujuan", "Aktif", "Akan Berakhir", "Berakhir", "Dibatalkan"].map((label) => ({ id: label, label, title: label === "Semua" ? "Kontrak & Perjanjian" : `Kontrak — ${label}`, description: "Kategori tampilan kontrak; status final menunggu keputusan sumber resmi.", caption: `Daftar kontrak ${label}`, columns, emptyDescription: "Data kontrak belum tersedia.", actions: label === "Semua" ? action : undefined, rows: [], children: label === "Semua" ? <><LegalUnavailableFormDrawer description="Form kontrak siap digunakan setelah sumber penyimpanan resmi tersedia." fields={fields} onClose={() => setOpen(false)} open={open} submitLabel="Simpan Kontrak" title="Tambah Kontrak" /><LegalExtractionDrawer onClose={() => setExtract(false)} open={extract} /></> : undefined })); return <LegalDataPage description="Kelola kesiapan review kontrak dan perjanjian tanpa menetapkan lifecycle final." tabs={tabs} title="Kontrak & Perjanjian" workspaceKey={workspaceKey} />; }
