"use client";
import { useState } from "react";
import { Button, type DataTableColumn } from "@/components/ui";
import { LegalDataPage, type LegalTab } from "../shared/legal-data-page";
import { LegalExtractionDrawer, LegalUnavailableFormDrawer, type LegalFormField } from "../shared/legal-ui";
type PermitRow = { readonly id: string };
const columns: readonly DataTableColumn<PermitRow>[] = ["Izin", "Jenis", "Proyek/Aset", "Penerbit", "Tanggal Terbit", "Efektif", "Berakhir", "Penanggung Jawab", "Status", "Perpanjangan", "Dokumen"].map((header) => ({ header, key: header, render: () => header === "Status" ? "Belum Dinilai" : "—" }));
const fields: readonly LegalFormField[] = [{ label: "Nama", name: "name", required: true }, { label: "Jenis", name: "type", required: true, select: true, sourceReady: false }, { label: "Penerbit", name: "issuer", required: true }, { label: "Nomor Referensi", name: "reference" }, { label: "Proyek / Aset", name: "project-asset", relation: true, sourceReady: false }, { label: "Penanggung Jawab", name: "owner", required: true, relation: true, sourceReady: false }, { label: "Tanggal Terbit", name: "issued", type: "date" }, { label: "Tanggal Efektif", name: "effective", type: "date" }, { label: "Tanggal Berakhir", name: "expires", type: "date" }, { label: "Perlu Perpanjangan", name: "renewal", select: true, sourceReady: false }, { label: "Kebutuhan Pengingat", name: "reminder" }, { label: "Dokumen", name: "document", required: true, relation: true, sourceReady: false }, { label: "Bukti", name: "evidence" }, { label: "Klasifikasi", name: "classification", required: true, select: true, sourceReady: false }];
const updateFields: readonly LegalFormField[] = [{ label: "Perizinan Asal", name: "original-permit", required: true, relation: true, sourceReady: false }, { label: "Perubahan yang Diajukan", name: "proposed-change", required: true, type: "textarea" }, { label: "Alasan", name: "reason", required: true, type: "textarea" }, { label: "Tanggal Berlaku", name: "effective-date", type: "date" }, { label: "Dokumen Pendukung", name: "document", relation: true, sourceReady: false }, { label: "Bukti", name: "evidence" }];
export function LegalPermitsPage({ workspaceKey }: Readonly<{ workspaceKey?: string }>) { const [open, setOpen] = useState(false); const [updateOpen, setUpdateOpen] = useState(false); const [extract, setExtract] = useState(false); const action = <><Button onClick={() => setOpen(true)}>Tambah Perizinan</Button><Button onClick={() => setUpdateOpen(true)} variant="secondary">Ajukan Pembaruan</Button><Button onClick={() => setExtract(true)} variant="secondary">Telaah Dokumen</Button></>; const tabs: readonly LegalTab<PermitRow>[] = ["Semua", "Aktif", "Mendekati Tenggat", "Berakhir", "Riwayat"].map((label) => ({ id: label, label, title: label === "Semua" ? "Perizinan" : `Perizinan — ${label}`, description: "Status izin menunggu sumber dan penilaian legal resmi; tenggat tidak dihitung di halaman ini.", caption: `Daftar perizinan ${label}`, columns, emptyDescription: "Data perizinan belum tersedia.", actions: label === "Semua" ? action : undefined, rows: [], children: label === "Semua" ? <><LegalUnavailableFormDrawer description="Form perizinan siap digunakan setelah sumber penyimpanan resmi tersedia." fields={fields} onClose={() => setOpen(false)} open={open} submitLabel="Simpan Perizinan" title="Tambah Perizinan" /><LegalUnavailableFormDrawer description="Pembaruan tidak mengubah validitas izin secara diam-diam; formulir ini hanya kesiapan UX." fields={updateFields} onClose={() => setUpdateOpen(false)} open={updateOpen} submitLabel="Simpan Pembaruan" title="Ajukan Pembaruan Perizinan" /><LegalExtractionDrawer onClose={() => setExtract(false)} open={extract} /></> : undefined })); return <LegalDataPage description="Pantau perizinan dan bukti pendukung tanpa menetapkan validitas secara mandiri." tabs={tabs} title="Perizinan" workspaceKey={workspaceKey} />; }
