"use client";

import { useState } from "react";
import { Button, DataTable, PageHeader, Section, Tabs, type TabItem } from "@/components/ui";
import { LegalLayout } from "../legal-layout";
import { LegalSourceStateView, LegalUnavailableFormDrawer, type LegalFormField } from "../shared/legal-ui";
import styles from "../legal.module.css";

const tabs: readonly TabItem[] = ["Menunggu Saya", "Dalam Review", "Dikembalikan", "Selesai", "Semua"].map((label) => ({ id: label, label }));
const columns = [{ header: "Subjek", key: "subject", render: () => "—" }, { header: "Jenis", key: "type", render: () => "—" }, { header: "Pemohon", key: "requester", render: () => "—" }, { header: "Divisi", key: "division", render: () => "—" }, { header: "Proyek", key: "project", render: () => "—" }, { header: "Diajukan", key: "submitted", render: () => "—" }, { header: "Prioritas", key: "priority", render: () => "Belum Dinilai" }, { header: "Materialitas", key: "materiality", render: () => "Belum Dinilai" }, { header: "Status", key: "status", render: () => "Belum Dinilai" }, { header: "SLA", key: "sla", render: () => "—" }];
const fields: readonly LegalFormField[] = [{ label: "Subjek", name: "subject", required: true }, { label: "Versi Dokumen", name: "document-version", required: true, relation: true, sourceReady: false }, { label: "Ruang Lingkup Review", name: "review-scope", required: true, type: "textarea" }, { label: "Penilaian", name: "assessment", select: true, sourceReady: false }, { label: "Isu", name: "issues", type: "textarea" }, { label: "Rekomendasi", name: "recommendation", type: "textarea" }, { label: "Kesimpulan", name: "conclusion", required: true, type: "textarea" }, { label: "Bukti", name: "evidence" }, { label: "Peninjau", name: "reviewer", relation: true, sourceReady: false }];

export function LegalReviewsPage({ workspaceKey }: Readonly<{ workspaceKey?: string }>) { return <LegalLayout workspaceKey={workspaceKey}>{() => <LegalReviews />}</LegalLayout>; }
function LegalReviews() { const [tab, setTab] = useState("Menunggu Saya"); const [open, setOpen] = useState(false); const actions = <><Button onClick={() => setOpen(true)}>Tambah Review</Button><Button disabled variant="secondary">Kembalikan</Button><Button disabled variant="secondary">Minta Perbaikan</Button><Button disabled variant="secondary">Catat Isu</Button></>; return <div className={styles.page}><PageHeader description="Telaah permintaan legal dengan pemisahan yang jelas dari persetujuan bisnis dan eksekusi tanda tangan." eyebrow="KONTRAK & DOKUMEN" title="Review Legal" /><Tabs ariaLabel="Navigasi review Legal" items={tabs} onValueChange={setTab} value={tab} /><Section actions={actions} description="Tindakan review menunggu sumber dan kewenangan resmi." title={tab}><DataTable caption={`Daftar review Legal — ${tab}`} columns={columns} emptyState={<LegalSourceStateView description={`Data review Legal pada bagian ${tab} belum tersedia.`} state="unavailable" />} rows={[]} /></Section><Section title="Pemisahan Status"><LegalSourceStateView description="Review Legal, persetujuan bisnis, dan eksekusi tanda tangan belum tersedia sebagai sumber terpisah." state="unavailable" /></Section><LegalUnavailableFormDrawer description="Form review siap digunakan setelah sumber penyimpanan resmi tersedia." fields={fields} onClose={() => setOpen(false)} open={open} submitLabel="Simpan Review" title="Tambah Review Legal" /></div>; }
