"use client";

import { useState } from "react";
import { Button, type DataTableColumn, type TabItem } from "@/components/ui";
import { FinanceDataPage } from "../shared/finance-data-page";
import { FinanceExtractionDrawer, FinanceUnavailableFormDrawer, type FinanceFormField } from "../shared/finance-ui";

interface TaxRow { readonly id: string; readonly type: string; readonly period: string; readonly transaction: string; readonly base: string; readonly amount: string; readonly due: string; readonly document: string; readonly payment: string; readonly reporting: string; readonly owner: string; }
const tabs: readonly TabItem[] = ["Kewajiban", "Jatuh Tempo", "Dokumen", "Pembayaran", "Pelaporan", "Riwayat"].map((label) => ({ id: label, label }));
const columns: readonly DataTableColumn<TaxRow>[] = ["Jenis", "Periode", "Transaksi Terkait", "Dasar Pajak", "Jumlah Pajak", "Jatuh Tempo", "Status Dokumen", "Status Pembayaran", "Status Pelaporan", "Penanggung Jawab"].map((header, index) => ({ header, key: `column-${index}`, render: (row) => Object.values(row)[index + 1] ?? "—" }));
const fields: readonly FinanceFormField[] = [{ label: "Jenis", name: "tax-type" }, { label: "Periode", name: "period" }, { label: "Transaksi Terkait", name: "related-transaction" }, { label: "Dasar Pajak", name: "tax-base", type: "number" }, { label: "Jumlah Pajak", name: "tax-amount", type: "number" }, { label: "Bukti Pendukung", name: "evidence" }, { label: "Penanggung Jawab", name: "owner" }];
export function FinanceTaxPage({ workspaceKey }: Readonly<{ workspaceKey?: string }>) { const [formOpen, setFormOpen] = useState(false); const [extractionOpen, setExtractionOpen] = useState(false); return <FinanceDataPage actions={<div><Button onClick={() => setFormOpen(true)}>Tambah Kewajiban</Button><Button onClick={() => setExtractionOpen(true)} variant="secondary">Telaah Dokumen</Button></div>} caption="Pajak dan kewajiban" columns={columns} description="Pantau kewajiban pajak, dokumen, pembayaran, dan pelaporan setelah sumber resmi tersedia." emptyDescription="Data kewajiban pajak belum tersedia." rows={[]} tabs={tabs} title="Pajak & Kewajiban" workspaceKey={workspaceKey}><FinanceUnavailableFormDrawer description="Data pajak menunggu sumber resmi dan aturan yang telah ditetapkan." fields={fields} onClose={() => setFormOpen(false)} open={formOpen} submitLabel="Simpan Kewajiban" title="Tambah Kewajiban Pajak" /><FinanceExtractionDrawer onClose={() => setExtractionOpen(false)} open={extractionOpen} /></FinanceDataPage>; }
