"use client";

import { useState } from "react";
import { Button, type DataTableColumn, type TabItem } from "@/components/ui";
import { FinanceDataPage } from "../shared/finance-data-page";
import { FinanceUnavailableFormDrawer, FinanceSectionNote, type FinanceFormField } from "../shared/finance-ui";

interface BudgetRow { readonly id: string; readonly name: string; readonly period: string; readonly owner: string; readonly division: string; readonly project: string; readonly plan: string; readonly committed: string; readonly actual: string; readonly forecast: string; readonly remaining: string; readonly variance: string; readonly status: string; }
const tabs: readonly TabItem[] = ["Anggaran", "Alokasi", "Komitmen", "Realisasi", "Perkiraan", "Revisi"].map((label) => ({ id: label, label }));
const columns: readonly DataTableColumn<BudgetRow>[] = ["Anggaran", "Periode", "Penanggung Jawab", "Divisi", "Proyek", "Rencana", "Komitmen", "Aktual", "Perkiraan", "Sisa", "Variansi", "Status"].map((header, index) => ({ header, key: `column-${index}`, render: (row) => Object.values(row)[index + 1] ?? "—" }));
const fields: readonly FinanceFormField[] = [{ label: "RKAP / Rencana", name: "plan" }, { label: "Nama Anggaran", name: "budget-name" }, { label: "Periode", name: "period" }, { label: "Ruang Lingkup", name: "scope" }, { label: "Penanggung Jawab", name: "owner" }, { label: "Jumlah", name: "amount", type: "number" }, { label: "Mata Uang", name: "currency" }, { label: "Alokasi", name: "allocation" }, { label: "Sumber", name: "source" }, { label: "Bukti", name: "evidence" }, { label: "Tingkat Kepentingan", name: "materiality" }];
export function FinanceBudgetPage({ workspaceKey }: Readonly<{ workspaceKey?: string }>) { const [open, setOpen] = useState(false); return <FinanceDataPage actions={<Button onClick={() => setOpen(true)}>Tambah Anggaran</Button>} caption="Anggaran finansial" columns={columns} description="Kelola tampilan anggaran finansial, komitmen, aktual, perkiraan, dan variansi secara terpisah dari RAB Property." emptyDescription="Anggaran finansial belum tersedia." rows={[]} tabs={tabs} title="Anggaran & Realisasi" workspaceKey={workspaceKey}><FinanceSectionNote>RAB dan BOQ teknis tetap berasal dari Property. Perubahan anggaran aktif tidak akan dianggap tersimpan sebelum sumber resmi tersedia.</FinanceSectionNote><FinanceUnavailableFormDrawer description="Form anggaran siap digunakan setelah sumber anggaran tersedia." fields={fields} onClose={() => setOpen(false)} open={open} submitLabel="Simpan Anggaran" title="Tambah Anggaran" /></FinanceDataPage>; }
