"use client";

import { useState } from "react";
import { Button, type DataTableColumn } from "@/components/ui";
import { FinanceDataPage, type FinanceTab } from "../shared/finance-data-page";
import { FinanceExtractionDrawer, FinanceUnavailableFormDrawer, type FinanceFormField } from "../shared/finance-ui";

interface BudgetRow { readonly id: string; readonly name: string; readonly period: string; readonly owner: string; readonly division: string; readonly project: string; readonly plan: string; readonly committed: string; readonly actual: string; readonly forecast: string; readonly remaining: string; readonly variance: string; readonly reason: string; readonly status: string; }
const budgetColumns: readonly DataTableColumn<BudgetRow>[] = [{ header: "Anggaran", key: "name", render: (row) => row.name }, { header: "Periode", key: "period", render: (row) => row.period }, { header: "Penanggung Jawab", key: "owner", render: (row) => row.owner }, { header: "Divisi", key: "division", render: (row) => row.division }, { header: "Proyek", key: "project", render: (row) => row.project }, { header: "Rencana", key: "plan", render: (row) => row.plan }, { header: "Komitmen", key: "committed", render: (row) => row.committed }, { header: "Aktual", key: "actual", render: (row) => row.actual }, { header: "Perkiraan", key: "forecast", render: (row) => row.forecast }, { header: "Sisa", key: "remaining", render: (row) => row.remaining }, { header: "Variansi", key: "variance", render: (row) => row.variance }, { header: "Status", key: "status", render: (row) => row.status }];
const allocationColumns: readonly DataTableColumn<BudgetRow>[] = [{ header: "Anggaran", key: "name", render: (row) => row.name }, { header: "Ruang Lingkup", key: "division", render: (row) => row.division }, { header: "Proyek", key: "project", render: (row) => row.project }, { header: "Alokasi", key: "plan", render: (row) => row.plan }, { header: "Sisa", key: "remaining", render: (row) => row.remaining }, { header: "Status", key: "status", render: (row) => row.status }];
const commitmentColumns: readonly DataTableColumn<BudgetRow>[] = [{ header: "Referensi Komitmen", key: "name", render: (row) => row.name }, { header: "Anggaran", key: "division", render: (row) => row.division }, { header: "Penerima", key: "owner", render: (row) => row.owner }, { header: "Jumlah", key: "committed", render: (row) => row.committed }, { header: "Proyek", key: "project", render: (row) => row.project }, { header: "Status", key: "status", render: (row) => row.status }];
const actualColumns: readonly DataTableColumn<BudgetRow>[] = [{ header: "Referensi", key: "name", render: (row) => row.name }, { header: "Anggaran", key: "division", render: (row) => row.division }, { header: "Tanggal", key: "period", render: (row) => row.period }, { header: "Aktual", key: "actual", render: (row) => row.actual }, { header: "Bukti", key: "reason", render: (row) => row.reason }, { header: "Status", key: "status", render: (row) => row.status }];
const forecastColumns: readonly DataTableColumn<BudgetRow>[] = [{ header: "Anggaran", key: "name", render: (row) => row.name }, { header: "Periode", key: "period", render: (row) => row.period }, { header: "Aktual", key: "actual", render: (row) => row.actual }, { header: "Perkiraan", key: "forecast", render: (row) => row.forecast }, { header: "Sisa", key: "remaining", render: (row) => row.remaining }, { header: "Status", key: "status", render: (row) => row.status }];
const revisionColumns: readonly DataTableColumn<BudgetRow>[] = [{ header: "Anggaran", key: "name", render: (row) => row.name }, { header: "Revisi", key: "reason", render: (row) => row.reason }, { header: "Periode", key: "period", render: (row) => row.period }, { header: "Penanggung Jawab", key: "owner", render: (row) => row.owner }, { header: "Status", key: "status", render: (row) => row.status }];
const budgetFields: readonly FinanceFormField[] = [{ label: "RKAP / Rencana", name: "plan", relation: true, sourceReady: false, required: true }, { label: "Nama Anggaran", name: "budget-name", required: true }, { label: "Periode", name: "period", required: true }, { label: "Ruang Lingkup", name: "scope", relation: true, sourceReady: false, required: true }, { label: "Penanggung Jawab", name: "owner", relation: true, sourceReady: false, required: true }, { label: "Jumlah", name: "amount", type: "number", required: true }, { label: "Mata Uang", name: "currency", required: true }, { label: "Alokasi", name: "allocation" }, { label: "Sumber", name: "source" }, { label: "Bukti", name: "evidence" }, { label: "Tingkat Kepentingan", name: "materiality" }];
const revisionFields: readonly FinanceFormField[] = [{ label: "Anggaran Aktif", name: "active-budget", relation: true, sourceReady: false, required: true }, { label: "Alasan Revisi", name: "revision-reason", type: "textarea", required: true }, { label: "Jumlah Revisi", name: "revision-amount", type: "number", required: true }, { label: "Bukti Pendukung", name: "revision-evidence", required: true }];

export function FinanceBudgetPage({ workspaceKey }: Readonly<{ workspaceKey?: string }>) {
  const [budgetOpen, setBudgetOpen] = useState(false);
  const [revisionOpen, setRevisionOpen] = useState(false);
  const [extractionOpen, setExtractionOpen] = useState(false);
  const budgetAction = <Button onClick={() => setBudgetOpen(true)}>Tambah Anggaran</Button>;
  const tabs: readonly FinanceTab<BudgetRow>[] = [
    { id: "budget", label: "Anggaran", title: "Anggaran", description: "Daftar anggaran finansial dengan rencana, komitmen, aktual, dan variansi terpisah.", caption: "Anggaran finansial", columns: budgetColumns, emptyDescription: "Anggaran finansial belum tersedia.", actions: budgetAction, rows: [], children: <FinanceUnavailableFormDrawer description="Form anggaran siap digunakan setelah sumber anggaran tersedia." fields={budgetFields} onClose={() => setBudgetOpen(false)} open={budgetOpen} submitLabel="Simpan Anggaran" title="Tambah Anggaran" /> },
    { id: "allocation", label: "Alokasi", title: "Alokasi Anggaran", description: "Pantau alokasi berdasarkan ruang lingkup dan proyek.", caption: "Alokasi anggaran", columns: allocationColumns, emptyDescription: "Alokasi anggaran belum tersedia.", rows: [] },
    { id: "commitment", label: "Komitmen", title: "Komitmen Anggaran", description: "Pantau nilai yang telah dikomitmenkan tanpa menyamakannya dengan pembayaran.", caption: "Komitmen anggaran", columns: commitmentColumns, emptyDescription: "Komitmen anggaran belum tersedia.", rows: [] },
    { id: "actual", label: "Realisasi", title: "Realisasi Anggaran", description: "Aktual keuangan berasal dari sumber Finance, bukan input ulang ringkasan.", caption: "Realisasi anggaran", columns: actualColumns, emptyDescription: "Realisasi anggaran belum tersedia.", rows: [] },
    { id: "forecast", label: "Perkiraan", title: "Perkiraan Anggaran", description: "Perkiraan dipisahkan dari rencana, komitmen, dan aktual.", caption: "Perkiraan anggaran", columns: forecastColumns, emptyDescription: "Perkiraan anggaran belum tersedia.", rows: [] },
    { id: "revision", label: "Revisi", title: "Revisi Anggaran", description: "Ajukan revisi tanpa menimpa anggaran aktif.", caption: "Revisi anggaran", columns: revisionColumns, emptyDescription: "Revisi anggaran belum tersedia.", actions: <div><Button onClick={() => setRevisionOpen(true)}>Ajukan Revisi Anggaran</Button><Button onClick={() => setExtractionOpen(true)} variant="secondary">Telaah Dokumen</Button></div>, rows: [], children: <><FinanceUnavailableFormDrawer description="Revisi dibuat sebagai pengajuan baru; anggaran aktif tidak ditimpa." fields={revisionFields} onClose={() => setRevisionOpen(false)} open={revisionOpen} submitLabel="Simpan Pengajuan Revisi" title="Ajukan Revisi Anggaran" /><FinanceExtractionDrawer onClose={() => setExtractionOpen(false)} open={extractionOpen} /></> },
  ];
  return <FinanceDataPage description="Kelola tampilan anggaran finansial, komitmen, aktual, perkiraan, dan variansi secara terpisah dari RAB Property." tabs={tabs} title="Anggaran & Realisasi" workspaceKey={workspaceKey} />;
}
