"use client";
import { useState } from "react";
import { Button, type DataTableColumn } from "@/components/ui";
import { LegalDataPage, type LegalTab } from "../shared/legal-data-page";
import { LegalSourceStateView, LegalUnavailableFormDrawer, type LegalFormField } from "../shared/legal-ui";

type RiskRow = { readonly id: string };
const columns: readonly DataTableColumn<RiskRow>[] = ["Risiko", "Kategori", "Objek Terkait", "Dampak", "Kemungkinan", "Severity", "Penanggung Jawab", "Mitigasi", "Tenggat", "Status", "Evidence"].map((header) => ({ header, key: header, render: () => header === "Status" || header === "Severity" ? "Belum Dinilai" : "—" }));
const fields: readonly LegalFormField[] = [{ label: "Judul Risiko", name: "title", required: true }, { label: "Kategori", name: "category", required: true, select: true, sourceReady: false }, { label: "Objek Terkait", name: "related-object", relation: true, sourceReady: false }, { label: "Dampak", name: "impact", type: "textarea" }, { label: "Kemungkinan", name: "likelihood", select: true, sourceReady: false, helper: "Pilihan penilaian menunggu sumber resmi." }, { label: "Severity", name: "severity", select: true, sourceReady: false }, { label: "Penanggung Jawab", name: "owner", required: true, relation: true, sourceReady: false }, { label: "Mitigasi", name: "mitigation", type: "textarea" }, { label: "Tenggat", name: "deadline", type: "date" }, { label: "Bukti", name: "evidence" }];
export function LegalRisksPage({ workspaceKey }: Readonly<{ workspaceKey?: string }>) { const [open, setOpen] = useState(false); const tabs: readonly LegalTab<RiskRow>[] = ["Risiko", "Kepatuhan", "Temuan", "Tindakan", "Riwayat"].map((label) => ({ id: label, label, title: label === "Risiko" ? "Risiko & Kepatuhan" : label, description: label === "Kepatuhan" ? "Persyaratan, bukti, penilaian, dan status menunggu sumber resmi." : `Tampilan ${label} Legal tanpa menyimpulkan status dari ketiadaan data.`, caption: `Daftar ${label} Legal`, columns, emptyDescription: `${label} Legal belum tersedia.`, rows: [], actions: label === "Risiko" ? <Button onClick={() => setOpen(true)}>Tambah Risiko</Button> : label === "Tindakan" ? <Button disabled variant="secondary">Buat Tindakan</Button> : undefined, children: label === "Risiko" ? <LegalUnavailableFormDrawer description="Form risiko siap digunakan setelah sumber penyimpanan resmi dan vocabulary tersedia." fields={fields} onClose={() => setOpen(false)} open={open} submitLabel="Simpan Risiko" title="Tambah Risiko Legal" /> : label === "Temuan" || label === "Tindakan" ? <LegalSourceStateView description="Temuan dan tindakan korektif menggunakan Shared Work setelah sumber resmi tersedia." state="unavailable" /> : undefined })); return <LegalDataPage description="Pantau risiko legal dan kepatuhan tanpa membuat penilaian atau status patuh dari halaman ini." tabs={tabs} title="Risiko & Kepatuhan" workspaceKey={workspaceKey} />; }
