"use client";
import { useState } from "react";
import { Button, type DataTableColumn } from "@/components/ui";
import { LegalDataPage, type LegalTab } from "../shared/legal-data-page";
import { LegalUnavailableFormDrawer, type LegalFormField } from "../shared/legal-ui";
type ObligationRow = { readonly id: string };
const columns: readonly DataTableColumn<ObligationRow>[] = ["Kewajiban", "Sumber", "Penanggung Jawab", "Tenggat", "Status", "Kebutuhan Bukti", "Objek Terkait", "Eskalasi"].map((header) => ({ header, key: header, render: () => header === "Status" ? "Belum Dinilai" : "—" }));
const fields: readonly LegalFormField[] = [{ label: "Objek Sumber", name: "source-object", required: true, relation: true, sourceReady: false }, { label: "Kewajiban", name: "obligation", required: true }, { label: "Pihak Bertanggung Jawab", name: "responsible-party", required: true, relation: true, sourceReady: false }, { label: "Penanggung Jawab", name: "owner", required: true, relation: true, sourceReady: false }, { label: "Tenggat", name: "deadline", type: "date", required: true, helper: "Tenggat harus berasal dari sumber resmi atau input manusia dengan bukti." }, { label: "Kebutuhan Bukti", name: "evidence-need" }, { label: "Status", name: "status", select: true, sourceReady: false }];
export function LegalObligationsPage({ workspaceKey }: Readonly<{ workspaceKey?: string }>) { const [open, setOpen] = useState(false); const tabs: readonly LegalTab<ObligationRow>[] = ["Semua", "Mendekati Tenggat", "Terlambat", "Selesai", "Riwayat"].map((label) => ({ id: label, label, title: label === "Semua" ? "Kewajiban & Tenggat" : `Kewajiban & Tenggat — ${label}`, description: "Pengingat hanya presentasi; halaman ini tidak mengarang tenggat atau mengubah status legal.", caption: `Daftar kewajiban ${label}`, columns, emptyDescription: "Data kewajiban dan tenggat belum tersedia.", actions: label === "Semua" ? <Button onClick={() => setOpen(true)}>Tambah Kewajiban</Button> : undefined, rows: [], children: label === "Semua" ? <LegalUnavailableFormDrawer description="Form kewajiban siap digunakan setelah sumber penyimpanan resmi tersedia." fields={fields} onClose={() => setOpen(false)} open={open} submitLabel="Simpan Kewajiban" title="Tambah Kewajiban" /> : undefined })); return <LegalDataPage description="Pantau kewajiban legal dan tenggat yang bersumber dari kontrak, izin, regulasi, kasus, atau corporate action." tabs={tabs} title="Kewajiban & Tenggat" workspaceKey={workspaceKey} />; }
