"use client";

import { useState } from "react";
import { Button, type DataTableColumn } from "@/components/ui";
import { FinanceDataPage, type FinanceTab } from "../shared/finance-data-page";
import { FinanceExtractionDrawer, FinanceUnavailableFormDrawer, type FinanceFormField } from "../shared/finance-ui";

interface PayablesRow { readonly id: string; readonly type: string; readonly recipient: string; readonly project: string; readonly invoice: string; readonly contract: string; readonly description: string; readonly amount: string; readonly due: string; readonly date: string; readonly verification: string; readonly payment: string; readonly settlement: string; readonly reconciliation: string; readonly status: string; }
const requestColumns: readonly DataTableColumn<PayablesRow>[] = [{ header: "Jenis Pembayaran", key: "type", render: (row) => row.type }, { header: "Penerima", key: "recipient", render: (row) => row.recipient }, { header: "Proyek", key: "project", render: (row) => row.project }, { header: "Deskripsi", key: "description", render: (row) => row.description }, { header: "Jumlah", key: "amount", render: (row) => row.amount }, { header: "Tanggal Kebutuhan", key: "due", render: (row) => row.due }, { header: "Status", key: "status", render: (row) => row.status }];
const invoiceColumns: readonly DataTableColumn<PayablesRow>[] = [{ header: "Referensi Invoice", key: "invoice", render: (row) => row.invoice }, { header: "Penerima", key: "recipient", render: (row) => row.recipient }, { header: "Referensi Kontrak", key: "contract", render: (row) => row.contract }, { header: "Jumlah", key: "amount", render: (row) => row.amount }, { header: "Tanggal", key: "date", render: (row) => row.date }, { header: "Bukti", key: "verification", render: (row) => row.verification }, { header: "Status", key: "status", render: (row) => row.status }];
const payableColumns: readonly DataTableColumn<PayablesRow>[] = [{ header: "Penerima", key: "recipient", render: (row) => row.recipient }, { header: "Referensi Invoice", key: "invoice", render: (row) => row.invoice }, { header: "Jumlah", key: "amount", render: (row) => row.amount }, { header: "Jatuh Tempo", key: "due", render: (row) => row.due }, { header: "Verifikasi", key: "verification", render: (row) => row.verification }, { header: "Status", key: "status", render: (row) => row.status }];
const readyColumns: readonly DataTableColumn<PayablesRow>[] = [{ header: "Penerima", key: "recipient", render: (row) => row.recipient }, { header: "Jumlah", key: "amount", render: (row) => row.amount }, { header: "Persetujuan", key: "verification", render: (row) => row.verification }, { header: "Rekening", key: "project", render: (row) => row.project }, { header: "Status", key: "status", render: (row) => row.status }];
const paymentColumns: readonly DataTableColumn<PayablesRow>[] = [{ header: "Referensi", key: "invoice", render: (row) => row.invoice }, { header: "Penerima", key: "recipient", render: (row) => row.recipient }, { header: "Jumlah", key: "amount", render: (row) => row.amount }, { header: "Pembayaran", key: "payment", render: (row) => row.payment }, { header: "Penyelesaian Transaksi", key: "settlement", render: (row) => row.settlement }, { header: "Rekonsiliasi", key: "reconciliation", render: (row) => row.reconciliation }, { header: "Status", key: "status", render: (row) => row.status }];
const dueColumns: readonly DataTableColumn<PayablesRow>[] = [{ header: "Penerima", key: "recipient", render: (row) => row.recipient }, { header: "Referensi", key: "invoice", render: (row) => row.invoice }, { header: "Jumlah", key: "amount", render: (row) => row.amount }, { header: "Jatuh Tempo", key: "due", render: (row) => row.due }, { header: "Umur", key: "date", render: (row) => row.date }, { header: "Status", key: "status", render: (row) => row.status }];
const requestFields: readonly FinanceFormField[] = [{ label: "Jenis Pembayaran", name: "payment-type", required: true }, { label: "Penerima", name: "recipient", required: true, relation: true, sourceReady: false }, { label: "Proyek", name: "project", relation: true, sourceReady: false }, { label: "Referensi Kontrak", name: "contract-reference", relation: true, sourceReady: false }, { label: "Referensi Invoice", name: "invoice-reference", relation: true, sourceReady: false }, { label: "Deskripsi", name: "description", type: "textarea", required: true }, { label: "Jumlah", name: "amount", type: "number", required: true }, { label: "Mata Uang", name: "currency", required: true }, { label: "Tanggal Kebutuhan", name: "need-date", type: "date" }, { label: "Referensi Anggaran", name: "budget-reference", relation: true, sourceReady: false }, { label: "Cost Center", name: "cost-center" }, { label: "Dokumen", name: "document", relation: true, sourceReady: false, required: true }, { label: "Bukti", name: "evidence", required: true }, { label: "Rekening Pembayaran", name: "payment-account", relation: true, sourceReady: false }];
const payableFields: readonly FinanceFormField[] = [{ label: "Penerima", name: "payable-recipient", required: true, relation: true, sourceReady: false }, { label: "Referensi Invoice", name: "payable-invoice", required: true, relation: true, sourceReady: false }, { label: "Referensi Kontrak", name: "payable-contract", relation: true, sourceReady: false }, { label: "Jumlah", name: "payable-amount", type: "number", required: true }, { label: "Mata Uang", name: "payable-currency", required: true }, { label: "Jatuh Tempo", name: "payable-due", type: "date" }, { label: "Dokumen", name: "payable-document", relation: true, sourceReady: false, required: true }, { label: "Bukti", name: "payable-evidence", required: true }];

export function FinancePayablesPage({ workspaceKey }: Readonly<{ workspaceKey?: string }>) {
  const [requestOpen, setRequestOpen] = useState(false);
  const [payableOpen, setPayableOpen] = useState(false);
  const [extractionOpen, setExtractionOpen] = useState(false);
  const requestAction = <Button onClick={() => setRequestOpen(true)}>Ajukan Pembayaran</Button>;
  const invoiceAction = <div><Button onClick={() => setPayableOpen(true)}>Catat Tagihan / Utang</Button><Button onClick={() => setExtractionOpen(true)} variant="secondary">Telaah Dokumen</Button></div>;
  const tabs: readonly FinanceTab<PayablesRow>[] = [
    { id: "requests", label: "Permintaan Bayar", title: "Permintaan Bayar", description: "Ajukan kebutuhan pembayaran tanpa menyatakan pembayaran telah selesai.", caption: "Permintaan pembayaran", columns: requestColumns, emptyDescription: "Permintaan pembayaran belum tersedia.", actions: requestAction, rows: [], children: <FinanceUnavailableFormDrawer description="Permintaan pembayaran menunggu penyimpanan resmi." fields={requestFields} onClose={() => setRequestOpen(false)} open={requestOpen} submitLabel="Simpan Permintaan" title="Permintaan Pembayaran" /> },
    { id: "invoices", label: "Tagihan / Invoice", title: "Tagihan / Invoice", description: "Catat tagihan secara terpisah dari permintaan dan eksekusi pembayaran.", caption: "Tagihan dan invoice", columns: invoiceColumns, emptyDescription: "Tagihan dan invoice belum tersedia.", actions: invoiceAction, rows: [], children: <><FinanceUnavailableFormDrawer description="Tagihan menunggu sumber penyimpanan resmi." fields={payableFields} onClose={() => setPayableOpen(false)} open={payableOpen} submitLabel="Simpan Tagihan" title="Catat Tagihan / Utang" /><FinanceExtractionDrawer onClose={() => setExtractionOpen(false)} open={extractionOpen} /></> },
    { id: "payables", label: "Utang", title: "Utang", description: "Pantau kewajiban kepada pihak lain berdasarkan tagihan yang tersedia.", caption: "Utang", columns: payableColumns, emptyDescription: "Utang belum tersedia.", actions: <Button onClick={() => setPayableOpen(true)}>Catat Tagihan / Utang</Button>, rows: [], children: <FinanceUnavailableFormDrawer description="Utang menunggu sumber penyimpanan resmi." fields={payableFields} onClose={() => setPayableOpen(false)} open={payableOpen} submitLabel="Simpan Tagihan" title="Catat Tagihan / Utang" /> },
    { id: "ready", label: "Siap Bayar", title: "Siap Bayar", description: "Daftar yang memenuhi prasyarat pembayaran setelah verifikasi resmi.", caption: "Siap bayar", columns: readyColumns, emptyDescription: "Daftar siap bayar belum tersedia.", rows: [] },
    { id: "payments", label: "Pembayaran", title: "Pembayaran", description: "Pantau pembayaran, penyelesaian transaksi, dan rekonsiliasi sebagai status terpisah.", caption: "Pembayaran", columns: paymentColumns, emptyDescription: "Pembayaran belum tersedia.", rows: [] },
    { id: "due", label: "Jatuh Tempo", title: "Pengeluaran Jatuh Tempo", description: "Pantau kewajiban yang mendekati atau melewati tanggal jatuh tempo.", caption: "Pengeluaran jatuh tempo", columns: dueColumns, emptyDescription: "Pengeluaran jatuh tempo belum tersedia.", rows: [] },
  ];
  return <FinanceDataPage description="Pisahkan permintaan bayar, persetujuan, pembayaran, penyelesaian transaksi, dan rekonsiliasi." tabs={tabs} title="Pengeluaran & Utang" workspaceKey={workspaceKey} />;
}
