"use client";

import { useState } from "react";
import { Button, type DataTableColumn, type TabItem } from "@/components/ui";
import { FinanceDataPage } from "../shared/finance-data-page";
import { FinanceUnavailableFormDrawer, FinanceSectionNote, type FinanceFormField } from "../shared/finance-ui";

interface PayableRow { readonly id: string; readonly type: string; readonly recipient: string; readonly project: string; readonly invoice: string; readonly description: string; readonly amount: string; readonly due: string; readonly status: string; }
const tabs: readonly TabItem[] = ["Permintaan Bayar", "Tagihan / Invoice", "Utang", "Siap Bayar", "Pembayaran", "Jatuh Tempo"].map((label) => ({ id: label, label }));
const columns: readonly DataTableColumn<PayableRow>[] = ["Jenis Pembayaran", "Penerima", "Proyek", "Referensi Invoice", "Deskripsi", "Jumlah", "Tanggal Kebutuhan", "Status"].map((header, index) => ({ header, key: `column-${index}`, render: (row) => Object.values(row)[index + 1] ?? "—" }));
const fields: readonly FinanceFormField[] = [{ label: "Jenis Pembayaran", name: "payment-type" }, { label: "Penerima", name: "recipient" }, { label: "Proyek", name: "project" }, { label: "Referensi Kontrak", name: "contract-reference" }, { label: "Referensi Invoice", name: "invoice-reference" }, { label: "Deskripsi", name: "description", type: "textarea" }, { label: "Jumlah", name: "amount", type: "number" }, { label: "Mata Uang", name: "currency" }, { label: "Tanggal Kebutuhan", name: "need-date", type: "date" }, { label: "Referensi Anggaran", name: "budget-reference" }, { label: "Cost Center", name: "cost-center" }, { label: "Dokumen", name: "document" }, { label: "Bukti", name: "evidence" }, { label: "Rekening Pembayaran", name: "payment-account" }];
export function FinancePayablesPage({ workspaceKey }: Readonly<{ workspaceKey?: string }>) { const [open, setOpen] = useState(false); return <FinanceDataPage actions={<Button onClick={() => setOpen(true)}>Ajukan Pembayaran</Button>} caption="Pengeluaran dan utang" columns={columns} description="Pisahkan permintaan bayar, persetujuan, pembayaran, settlement, dan rekonsiliasi." emptyDescription="Pengeluaran dan utang belum tersedia." rows={[]} tabs={tabs} title="Pengeluaran & Utang" workspaceKey={workspaceKey}><FinanceSectionNote>Persetujuan tidak sama dengan pembayaran. Pembayaran tidak sama dengan settlement atau rekonsiliasi.</FinanceSectionNote><FinanceUnavailableFormDrawer description="Form permintaan pembayaran siap digunakan setelah penyimpanan resmi tersedia." fields={fields} onClose={() => setOpen(false)} open={open} submitLabel="Simpan Permintaan" title="Permintaan Pembayaran" /></FinanceDataPage>; }
