import { authenticatedApiRequest } from "@/lib/api";
import { recordApi } from "@/features/business-records/record-api";
import type {
  FinanceBankAccountCreateRequest,
  FinanceBankAccountUpdateRequest,
  FinanceBankAccountProjection,
  FinanceBankAccountListProjection,
  FinanceBankAccountTransitionRequest,
  FinanceBankTransactionCreateRequest,
  FinanceBankTransactionUpdateRequest,
  FinanceBankTransactionProjection,
  FinanceBankTransactionListProjection,
  FinanceBankTransactionTransitionRequest,
  FinanceReceivableCreateRequest,
  FinanceReceivableUpdateRequest,
  FinanceReceivableProjection,
  FinanceReceivableListProjection,
  FinanceReceivableTransitionRequest,
  FinanceReceivablePaymentCreateRequest,
  FinanceReceivablePaymentUpdateRequest,
  FinanceReceivablePaymentProjection,
  FinanceReceivablePaymentListProjection,
  FinanceReceivablePaymentTransitionRequest,
  FinancePayableCreateRequest,
  FinancePayableUpdateRequest,
  FinancePayableProjection,
  FinancePayableListProjection,
  FinancePayableTransitionRequest,
  FinancePayablePaymentCreateRequest,
  FinancePayablePaymentUpdateRequest,
  FinancePayablePaymentProjection,
  FinancePayablePaymentListProjection,
  FinancePayablePaymentTransitionRequest,
  FinanceBudgetCreateRequest,
  FinanceBudgetUpdateRequest,
  FinanceBudgetProjection,
  FinanceBudgetListProjection,
  FinanceBudgetTransitionRequest,
  FinanceBudgetLineCreateRequest,
  FinanceBudgetLineUpdateRequest,
  FinanceBudgetLineProjection,
  FinanceBudgetLineListProjection,
  FinanceReconciliationCreateRequest,
  FinanceReconciliationUpdateRequest,
  FinanceReconciliationProjection,
  FinanceReconciliationListProjection,
  FinanceReconciliationTransitionRequest,
  FinanceReconciliationItemCreateRequest,
  FinanceReconciliationItemUpdateRequest,
  FinanceReconciliationItemProjection,
  FinanceReconciliationItemListProjection,
  FinanceReconciliationItemTransitionRequest,
  FinanceTaxObligationCreateRequest,
  FinanceTaxObligationUpdateRequest,
  FinanceTaxObligationProjection,
  FinanceTaxObligationListProjection,
  FinanceTaxObligationTransitionRequest,
  FinanceTaxDocumentCreateRequest,
  FinanceTaxDocumentUpdateRequest,
  FinanceTaxDocumentProjection,
  FinanceTaxDocumentListProjection,
  FinanceTaxDocumentTransitionRequest,
  FinanceMonthCloseCreateRequest,
  FinanceMonthCloseUpdateRequest,
  FinanceMonthCloseProjection,
  FinanceMonthCloseListProjection,
  FinanceMonthCloseTransitionRequest,
  FinanceMonthCloseItemCreateRequest,
  FinanceMonthCloseItemUpdateRequest,
  FinanceMonthCloseItemProjection,
  FinanceMonthCloseItemListProjection,
  FinanceMonthCloseItemTransitionRequest,
  FinanceOverview
} from "@/lib/contracts";

export const financeApi = {
  overview(signal?: AbortSignal) { return authenticatedApiRequest<FinanceOverview>("/api/v1/finance/overview", { signal }); },
  bank_accounts: recordApi<FinanceBankAccountCreateRequest, FinanceBankAccountUpdateRequest, FinanceBankAccountProjection, FinanceBankAccountListProjection, FinanceBankAccountTransitionRequest>("/api/v1/finance/bank-accounts"),
  bank_transactions: recordApi<FinanceBankTransactionCreateRequest, FinanceBankTransactionUpdateRequest, FinanceBankTransactionProjection, FinanceBankTransactionListProjection, FinanceBankTransactionTransitionRequest>("/api/v1/finance/bank-transactions"),
  receivables: recordApi<FinanceReceivableCreateRequest, FinanceReceivableUpdateRequest, FinanceReceivableProjection, FinanceReceivableListProjection, FinanceReceivableTransitionRequest>("/api/v1/finance/receivables"),
  receivable_payments: recordApi<FinanceReceivablePaymentCreateRequest, FinanceReceivablePaymentUpdateRequest, FinanceReceivablePaymentProjection, FinanceReceivablePaymentListProjection, FinanceReceivablePaymentTransitionRequest>("/api/v1/finance/receivable-payments"),
  payables: recordApi<FinancePayableCreateRequest, FinancePayableUpdateRequest, FinancePayableProjection, FinancePayableListProjection, FinancePayableTransitionRequest>("/api/v1/finance/payables"),
  payable_payments: recordApi<FinancePayablePaymentCreateRequest, FinancePayablePaymentUpdateRequest, FinancePayablePaymentProjection, FinancePayablePaymentListProjection, FinancePayablePaymentTransitionRequest>("/api/v1/finance/payable-payments"),
  budgets: recordApi<FinanceBudgetCreateRequest, FinanceBudgetUpdateRequest, FinanceBudgetProjection, FinanceBudgetListProjection, FinanceBudgetTransitionRequest>("/api/v1/finance/budgets"),
  budget_lines: recordApi<FinanceBudgetLineCreateRequest, FinanceBudgetLineUpdateRequest, FinanceBudgetLineProjection, FinanceBudgetLineListProjection, object>("/api/v1/finance/budget-lines"),
  reconciliations: recordApi<FinanceReconciliationCreateRequest, FinanceReconciliationUpdateRequest, FinanceReconciliationProjection, FinanceReconciliationListProjection, FinanceReconciliationTransitionRequest>("/api/v1/finance/reconciliations"),
  reconciliation_items: recordApi<FinanceReconciliationItemCreateRequest, FinanceReconciliationItemUpdateRequest, FinanceReconciliationItemProjection, FinanceReconciliationItemListProjection, FinanceReconciliationItemTransitionRequest>("/api/v1/finance/reconciliation-items"),
  tax_obligations: recordApi<FinanceTaxObligationCreateRequest, FinanceTaxObligationUpdateRequest, FinanceTaxObligationProjection, FinanceTaxObligationListProjection, FinanceTaxObligationTransitionRequest>("/api/v1/finance/tax-obligations"),
  tax_documents: recordApi<FinanceTaxDocumentCreateRequest, FinanceTaxDocumentUpdateRequest, FinanceTaxDocumentProjection, FinanceTaxDocumentListProjection, FinanceTaxDocumentTransitionRequest>("/api/v1/finance/tax-documents"),
  month_closes: recordApi<FinanceMonthCloseCreateRequest, FinanceMonthCloseUpdateRequest, FinanceMonthCloseProjection, FinanceMonthCloseListProjection, FinanceMonthCloseTransitionRequest>("/api/v1/finance/month-closes"),
  month_close_items: recordApi<FinanceMonthCloseItemCreateRequest, FinanceMonthCloseItemUpdateRequest, FinanceMonthCloseItemProjection, FinanceMonthCloseItemListProjection, FinanceMonthCloseItemTransitionRequest>("/api/v1/finance/month-close-items"),
};
