"use client";

import { useState } from "react";
import { Button, type DataTableColumn } from "@/components/ui";
import { FinanceDataPage, type FinanceTab } from "../shared/finance-data-page";
import { FinanceExtractionDrawer, FinanceUnavailableFormDrawer, type FinanceFormField } from "../shared/finance-ui";

interface ReceivablesRow { readonly id: string; readonly reference: string; readonly party: string; readonly source: string; readonly project: string; readonly amount: string; readonly issued: string; readonly due: string; readonly age: string; readonly method: string; readonly verification: string; readonly reconciliation: string; readonly status: string; readonly owner: string; readonly evidence: string; }
const receiptColumns: readonly DataTableColumn<ReceivablesRow>[] = [{ header: "Referensi", key: "reference", render: (row) => row.reference }, { header: "Pihak", key: "party", render: (row) => row.party }, { header: "Sumber", key: "source", render: (row) => row.source }, { header: "Proyek", key: "project", render: (row) => row.project }, { header: "Jumlah", key: "amount", render: (row) => row.amount }, { header: "Tanggal", key: "issued", render: (row) => row.issued }, { header: "Metode Pembayaran", key: "method", render: (row) => row.method }, { header: "Verifikasi", key: "verification", render: (row) => row.verification }, { header: "Rekonsiliasi", key: "reconciliation", render: (row) => row.reconciliation }, { header: "Status", key: "status", render: (row) => row.status }];
const receivableColumns: readonly DataTableColumn<ReceivablesRow>[] = [{ header: "Pihak", key: "party", render: (row) => row.party }, { header: "Sumber", key: "source", render: (row) => row.source }, { header: "Proyek", key: "project", render: (row) => row.project }, { header: "Referensi", key: "reference", render: (row) => row.reference }, { header: "Jumlah", key: "amount", render: (row) => row.amount }, { header: "Outstanding", key: "outstanding", render: (row) => row.amount }, { header: "Jatuh Tempo", key: "due", render: (row) => row.due }, { header: "Umur", key: "age", render: (row) => row.age }, { header: "Status", key: "status", render: (row) => row.status }, { header: "Penanggung Jawab", key: "owner", render: (row) => row.owner }, { header: "Bukti", key: "evidence", render: (row) => row.evidence }];
const agingColumns: readonly DataTableColumn<ReceivablesRow>[] = [{ header: "Pihak", key: "party", render: (row) => row.party }, { header: "Referensi", key: "reference", render: (row) => row.reference }, { header: "Jumlah", key: "amount", render: (row) => row.amount }, { header: "Jatuh Tempo", key: "due", render: (row) => row.due }, { header: "Umur", key: "age", render: (row) => row.age }, { header: "Status", key: "status", render: (row) => row.status }];
const refundColumns: readonly DataTableColumn<ReceivablesRow>[] = [{ header: "Referensi Penerimaan", key: "reference", render: (row) => row.reference }, { header: "Pihak", key: "party", render: (row) => row.party }, { header: "Jumlah", key: "amount", render: (row) => row.amount }, { header: "Tanggal Pengajuan", key: "issued", render: (row) => row.issued }, { header: "Verifikasi", key: "verification", render: (row) => row.verification }, { header: "Status", key: "status", render: (row) => row.status }];
const historyColumns: readonly DataTableColumn<ReceivablesRow>[] = [{ header: "Referensi", key: "reference", render: (row) => row.reference }, { header: "Pihak", key: "party", render: (row) => row.party }, { header: "Peristiwa", key: "source", render: (row) => row.source }, { header: "Jumlah", key: "amount", render: (row) => row.amount }, { header: "Tanggal", key: "issued", render: (row) => row.issued }, { header: "Status", key: "status", render: (row) => row.status }];

const receiptFields: readonly FinanceFormField[] = [{ label: "Tanggal", name: "date", type: "date", required: true }, { label: "Pihak", name: "party", required: true }, { label: "Jenis Penerimaan", name: "receipt-type", required: true }, { label: "Referensi Bisnis", name: "business-reference" }, { label: "Proyek", name: "project", relation: true, sourceReady: false }, { label: "Jumlah", name: "amount", type: "number", required: true }, { label: "Mata Uang", name: "currency", required: true }, { label: "Metode Pembayaran", name: "payment-method" }, { label: "Rekening", name: "account", relation: true, sourceReady: false, required: true }, { label: "Mode Sumber", name: "source-mode", required: true }, { label: "Bukti", name: "evidence", required: true }, { label: "Deskripsi", name: "description", type: "textarea" }];
const receivableFields: readonly FinanceFormField[] = [{ label: "Pihak", name: "party", required: true }, { label: "Sumber", name: "source", required: true }, { label: "Jumlah", name: "amount", type: "number", required: true }, { label: "Mata Uang", name: "currency", required: true }, { label: "Tanggal Terbit", name: "issued", type: "date", required: true }, { label: "Jatuh Tempo", name: "due", type: "date", required: true }, { label: "Referensi", name: "reference" }, { label: "Proyek", name: "project", relation: true, sourceReady: false }, { label: "Penanggung Jawab", name: "owner", relation: true, sourceReady: false }, { label: "Bukti", name: "evidence", required: true }];
const refundFields: readonly FinanceFormField[] = [{ label: "Pihak", name: "refund-party", required: true }, { label: "Referensi Penerimaan", name: "refund-receipt-reference", required: true }, { label: "Alasan", name: "refund-reason", type: "textarea", required: true }, { label: "Jumlah", name: "refund-amount", type: "number", required: true }, { label: "Bukti Pendukung", name: "refund-evidence", required: true }];

export function FinanceReceivablesPage({ workspaceKey }: Readonly<{ workspaceKey?: string }>) {
  const [receiptOpen, setReceiptOpen] = useState(false);
  const [receivableOpen, setReceivableOpen] = useState(false);
  const [refundOpen, setRefundOpen] = useState(false);
  const [extractionOpen, setExtractionOpen] = useState(false);
  const receiptActions = <div><Button onClick={() => setReceiptOpen(true)}>Tambah Penerimaan</Button><Button onClick={() => setExtractionOpen(true)} variant="secondary">Telaah Dokumen</Button></div>;
  const tabs: readonly FinanceTab<ReceivablesRow>[] = [
    { id: "receipts", label: "Penerimaan", title: "Penerimaan", description: "Catat dan pantau penerimaan dengan verifikasi terpisah.", caption: "Penerimaan", columns: receiptColumns, emptyDescription: "Penerimaan belum tersedia.", actions: receiptActions, rows: [], children: <><FinanceUnavailableFormDrawer description="Lengkapi data penerimaan tanpa menganggapnya telah diverifikasi." fields={receiptFields} onClose={() => setReceiptOpen(false)} open={receiptOpen} submitLabel="Simpan Penerimaan" title="Tambah Penerimaan" /><FinanceExtractionDrawer onClose={() => setExtractionOpen(false)} open={extractionOpen} /></> },
    { id: "receivables", label: "Piutang", title: "Piutang", description: "Pantau piutang dan outstanding berdasarkan sumber resmi.", caption: "Piutang", columns: receivableColumns, emptyDescription: "Piutang belum tersedia.", actions: <Button onClick={() => setReceivableOpen(true)}>Tambah Piutang</Button>, rows: [], children: <FinanceUnavailableFormDrawer description="Piutang menunggu sumber penyimpanan resmi." fields={receivableFields} onClose={() => setReceivableOpen(false)} open={receivableOpen} submitLabel="Simpan Piutang" title="Tambah Piutang" /> },
    { id: "due", label: "Jatuh Tempo", title: "Piutang Jatuh Tempo", description: "Daftar piutang yang mendekati atau mencapai tanggal jatuh tempo.", caption: "Piutang jatuh tempo", columns: agingColumns, emptyDescription: "Piutang jatuh tempo belum tersedia.", rows: [] },
    { id: "overdue", label: "Terlambat", title: "Piutang Terlambat", description: "Daftar piutang yang melewati tanggal jatuh tempo.", caption: "Piutang terlambat", columns: agingColumns, emptyDescription: "Piutang terlambat belum tersedia.", rows: [] },
    { id: "refund", label: "Refund", title: "Refund", description: "Pantau permintaan refund tanpa menyimpulkan refund telah dibayar.", caption: "Permintaan refund", columns: refundColumns, emptyDescription: "Permintaan refund belum tersedia.", actions: <Button onClick={() => setRefundOpen(true)}>Ajukan Refund</Button>, rows: [], children: <FinanceUnavailableFormDrawer description="Permintaan refund menunggu sumber verifikasi dan penyimpanan resmi." fields={refundFields} onClose={() => setRefundOpen(false)} open={refundOpen} submitLabel="Simpan Permintaan Refund" title="Ajukan Refund" /> },
    { id: "history", label: "Riwayat", title: "Riwayat Penerimaan", description: "Riwayat penerimaan, piutang, dan refund yang telah tercatat.", caption: "Riwayat penerimaan", columns: historyColumns, emptyDescription: "Riwayat penerimaan belum tersedia.", rows: [] },
  ];
  return <FinanceDataPage description="Pantau penerimaan dan piutang dengan status verifikasi yang terpisah dari pelunasan." tabs={tabs} title="Penerimaan & Piutang" workspaceKey={workspaceKey} />;
}
