"use client";

import { useState } from "react";
import { Button, type DataTableColumn, type TabItem } from "@/components/ui";
import { FinanceDataPage } from "../shared/finance-data-page";
import { FinanceUnavailableFormDrawer, FinanceSectionNote, type FinanceFormField } from "../shared/finance-ui";

interface ReceiptRow { readonly id: string; readonly reference: string; readonly party: string; readonly source: string; readonly project: string; readonly amount: string; readonly date: string; readonly method: string; readonly verification: string; readonly reconciliation: string; readonly status: string; }
const tabs: readonly TabItem[] = ["Penerimaan", "Piutang", "Jatuh Tempo", "Terlambat", "Refund", "Riwayat"].map((label) => ({ id: label, label }));
const columns: readonly DataTableColumn<ReceiptRow>[] = ["Referensi", "Pihak", "Sumber", "Proyek", "Jumlah", "Tanggal", "Metode Pembayaran", "Verifikasi", "Rekonsiliasi", "Status"].map((header, index) => ({ header, key: `column-${index}`, render: (row) => Object.values(row)[index + 1] ?? "—" }));
const receiptFields: readonly FinanceFormField[] = [{ label: "Tanggal", name: "date", type: "date" }, { label: "Pihak", name: "party" }, { label: "Jenis Penerimaan", name: "receipt-type" }, { label: "Referensi Bisnis", name: "business-reference" }, { label: "Proyek", name: "project" }, { label: "Jumlah", name: "amount", type: "number" }, { label: "Mata Uang", name: "currency" }, { label: "Metode Pembayaran", name: "payment-method" }, { label: "Rekening", name: "account" }, { label: "Mode Sumber", name: "source-mode" }, { label: "Bukti", name: "evidence" }, { label: "Deskripsi", name: "description", type: "textarea" }];
const refundFields: readonly FinanceFormField[] = [{ label: "Pihak", name: "refund-party" }, { label: "Referensi Penerimaan", name: "refund-receipt-reference" }, { label: "Alasan", name: "refund-reason", type: "textarea" }, { label: "Jumlah", name: "refund-amount", type: "number" }, { label: "Bukti Pendukung", name: "refund-evidence" }];
export function FinanceReceivablesPage({ workspaceKey }: Readonly<{ workspaceKey?: string }>) { const [receiptOpen, setReceiptOpen] = useState(false); const [refundOpen, setRefundOpen] = useState(false); return <FinanceDataPage actions={<div><Button onClick={() => setReceiptOpen(true)}>Tambah Penerimaan</Button><Button onClick={() => setRefundOpen(true)} variant="secondary">Ajukan Refund</Button></div>} caption="Penerimaan dan piutang" columns={columns} description="Pantau penerimaan dan piutang dengan status verifikasi yang terpisah dari pelunasan." emptyDescription="Penerimaan dan piutang belum tersedia." rows={[]} tabs={tabs} title="Penerimaan & Piutang" workspaceKey={workspaceKey}><FinanceSectionNote>Catatan: penerimaan manual secara konseptual dimulai sebagai Menunggu Verifikasi. Tombol simpan menunggu tersedianya penyimpanan resmi.</FinanceSectionNote><FinanceUnavailableFormDrawer description="Lengkapi data penerimaan tanpa menganggapnya telah diverifikasi." fields={receiptFields} onClose={() => setReceiptOpen(false)} open={receiptOpen} submitLabel="Simpan Penerimaan" title="Tambah Penerimaan" /><FinanceUnavailableFormDrawer description="Permintaan refund menunggu sumber verifikasi dan penyimpanan resmi." fields={refundFields} onClose={() => setRefundOpen(false)} open={refundOpen} submitLabel="Simpan Permintaan Refund" title="Ajukan Refund" /></FinanceDataPage>; }
