import type { BusinessUnit, MeasurementType } from "./enums";

export type BusinessDashboardKey = "executive" | "sales" | "property" | "finance" | "legal" | "hr" | "it";
export interface MetricRequirement { readonly code: string; readonly name: string; readonly measurement_type: MeasurementType; readonly unit: BusinessUnit; }
export interface DashboardRequirement { readonly label: string; readonly areas: readonly string[]; readonly metrics: readonly MetricRequirement[]; }

const metric = (code: string, name: string, measurement_type: MeasurementType = "PERCENTAGE", unit: BusinessUnit = "PERCENT"): MetricRequirement => ({ code, name, measurement_type, unit });
export const DASHBOARD_REQUIREMENTS: Record<BusinessDashboardKey, DashboardRequirement> = {
  executive: { label: "Executive Command Center", areas: ["Data Freshness & Company Status", "Business Headline", "Corporate Target Performance", "Commercial & Sales Funnel", "Financial Health", "Project & Construction Delivery", "Legal / Permit / KPR Health", "Workforce & Organization Health", "IT & ALOS Health", "Division Health", "Early Warning", "Decision Queue", "GENESIS Intelligence", "Reporting & Governance Cadence"], metrics: [metric("HEADLINE-REVENUE", "Revenue", "CUMULATIVE", "IDR"), metric("HEADLINE-CLOSING", "Closing", "CUMULATIVE", "COUNT"), metric("HEADLINE-LIQUIDITY", "Cash / Liquidity", "EXACT", "IDR"), metric("HEADLINE-DELIVERY", "Project Delivery"), metric("HEADLINE-DECISIONS", "Pending Decisions", "LOWER_IS_BETTER", "COUNT"), metric("HEADLINE-RISK", "Governance / Risk", "LOWER_IS_BETTER", "COUNT")] },
  sales: { label: "Sales & Marketing", areas: ["Performance Headline", "Commercial Funnel", "Lead Quality", "Response & Follow-up", "Channel Attribution", "Campaign Performance", "KPR/Akad Pipeline", "Cancellation", "Control Cadence", "Data Readiness", "AI Support"], metrics: [metric("KPI-SM-01", "Closing Klaten", "CUMULATIVE", "COUNT"), metric("KPI-SM-02", "Closing The Park", "CUMULATIVE", "COUNT"), metric("KPI-SM-03", "Lead Response SLA", "LOWER_IS_BETTER", "MINUTE"), metric("KPI-SM-04", "Survey-to-Closing Conversion"), metric("KPI-SM-05", "CPL", "LOWER_IS_BETTER", "IDR"), metric("KPI-SM-06", "Cancellation Rate", "LOWER_IS_BETTER") ] },
  property: { label: "Property & Construction", areas: ["Project Portfolio", "S-Curve Planned vs Actual", "Budget vs RAB", "Construction Milestones", "7 Hold Points", "K3", "Defect & Retention", "Geotag Evidence", "Contractor Opname", "Material / Delivery Risk", "Control Cadence", "Data Readiness", "AI Support"], metrics: [metric("KPI-PR-01", "S-Curve Deviation", "RANGE"), metric("KPI-PR-02", "Cost vs RAB", "RANGE", "IDR"), metric("KPI-PR-03", "Hold Point Compliance"), metric("KPI-PR-04", "K3 Fatality", "EXACT", "COUNT"), metric("KPI-PR-05", "Technical Survey Support", "MILESTONE", "COUNT"), metric("KPI-PR-06", "Contractor Opname SLA", "LOWER_IS_BETTER", "DAY") ] },
  finance: { label: "Finance", areas: ["Cash Position", "Bank Wallets", "Cash In / Cash Out", "Budget vs Actual", "Receivables", "Payables", "Bank Reconciliation", "KPR Disbursement", "Tax", "Month Close", "Approval Queue", "Control Cadence", "Data Readiness", "AI Support"], metrics: [metric("KPI-FN-01", "Bank Reconciliation"), metric("KPI-FN-02", "Budget Compliance"), metric("KPI-FN-03", "Vendor Payment SLA", "LOWER_IS_BETTER", "DAY"), metric("KPI-FN-04", "KPR Disbursement SLA", "LOWER_IS_BETTER", "DAY"), metric("KPI-FN-05", "Tax Reporting", "MILESTONE", "BOOLEAN"), metric("KPI-FN-06", "Receivable Collectability")] },
  legal: { label: "Legal & Compliance", areas: ["Land Legal Status", "Certificates", "Permits", "Contract Review", "KPR / Notary Pipeline", "Permit Expiry", "PDP Compliance", "Disputes / Cases", "Legal Risk", "Control Cadence", "Data Readiness", "AI Support"], metrics: [metric("KPI-LG-01", "Certificate Split Completion"), metric("KPI-LG-02", "Contract Review SLA", "LOWER_IS_BETTER", "DAY"), metric("KPI-LG-03", "PBG / SLF", "MILESTONE", "BOOLEAN"), metric("KPI-LG-04", "PDP Compliance"), metric("KPI-LG-05", "KPR Legal File Validity"), metric("KPI-LG-06", "Permit Expiry", "LOWER_IS_BETTER", "DAY")] },
  hr: { label: "HR & People", areas: ["Headcount", "Attendance", "Timesheet", "Payroll", "Recruitment", "Training", "Performance", "Segregation-of-Duties Compliance", "Employee Retention", "Personnel Administration", "Control Cadence", "Data Readiness", "AI Support"], metrics: [metric("KPI-HR-01", "Attendance & Timesheet"), metric("KPI-HR-02", "Payroll Accuracy"), metric("KPI-HR-03", "Training Hours", "HIGHER_IS_BETTER", "HOUR"), metric("KPI-HR-04", "SoD Compliance"), metric("KPI-HR-05", "Recruitment SLA", "LOWER_IS_BETTER", "DAY"), metric("KPI-HR-06", "Core Employee Retention")] },
  it: { label: "IT & GENESIS", areas: ["System Health", "Integrations", "Database", "Environments", "Repositories", "CI/CD", "Releases", "Monitoring", "Security", "Incidents", "Backup & Disaster Recovery", "AI Cost", "GENESIS Runtime", "Control Cadence", "Data Readiness"], metrics: [metric("KPI-IT-01", "ALOS Uptime"), metric("KPI-IT-02", "P0 Incident SLA", "LOWER_IS_BETTER", "MINUTE"), metric("KPI-IT-03", "AI Token Budget Compliance"), metric("KPI-IT-04", "Multi-Tenant Isolation", "BINARY", "BOOLEAN"), metric("KPI-IT-05", "External Portal Response", "LOWER_IS_BETTER", "MINUTE"), metric("KPI-IT-06", "Backup Success")] },
};

export const SALES_PIPELINE = ["Lead", "Qualified", "Survey", "Booking Fee", "SPK", "KPR Submitted", "SP3K", "Akad"] as const;
