import type { BusinessScopeType, BusinessUnit, CadenceFrequency, DataReadinessState, LifecycleState, MeasurementType, MetricValueKind, PerformanceState, PeriodGranularity, RevisionState, VerificationState } from "./enums";

/**
 * Frontend presentation models for MVP-2 Stage 1.
 * They are NOT canonical Backend contracts and MUST NOT be treated as authoritative business state.
 * IDs are opaque references supplied by an authoritative source; this layer never creates canonical identity or authority rules.
 */
export interface BusinessPeriod { readonly label: string | null; readonly granularity: PeriodGranularity; readonly starts_at: string | null; readonly ends_at: string | null; }
export interface BusinessScope { readonly type: BusinessScopeType; readonly ref: string | null; readonly label: string | null; }
export interface BusinessSourceRef { readonly source_ref: string | null; readonly label: string | null; readonly authoritative: boolean; readonly readiness: DataReadinessState; readonly observed_at: string | null; }
export interface BusinessEvidenceRef { readonly evidence_ref: string | null; readonly label: string | null; readonly uri: string | null; readonly captured_at: string | null; readonly verification_state: VerificationState; }
export interface BusinessAuthorityRef { readonly owner_role_ref: string | null; readonly owner_workspace_ref: string | null; readonly reviewer_role_refs: readonly string[]; readonly approver_role_ref: string | null; }

export interface MetricDefinition { readonly metric_id: string; readonly code: string; readonly name: string; readonly description: string | null; readonly measurement_type: MeasurementType; readonly unit: BusinessUnit; readonly default_scope: BusinessScope | null; readonly lifecycle_state: LifecycleState; }
export interface MetricObservation { readonly kind: MetricValueKind; readonly value: number | string | boolean | null; readonly period: BusinessPeriod | null; readonly unit: BusinessUnit; readonly source: BusinessSourceRef | null; readonly observed_at: string | null; readonly verified_at: string | null; readonly evidence_refs: readonly BusinessEvidenceRef[]; readonly verification_state: VerificationState; }
export interface PerformanceMetric extends BusinessAuthorityRef { readonly metric_id: string; readonly code: string; readonly name: string; readonly description: string | null; readonly measurement_type: MeasurementType; readonly unit: BusinessUnit; readonly scope: BusinessScope | null; readonly period: BusinessPeriod | null; readonly target: MetricObservation | null; readonly actual: MetricObservation | null; readonly forecast: MetricObservation | null; readonly assumption: MetricObservation | null; readonly variance: number | null; readonly achievement_percent: number | null; readonly performance_state: PerformanceState; readonly source_refs: readonly BusinessSourceRef[]; readonly evidence_refs: readonly BusinessEvidenceRef[]; readonly last_updated_at: string | null; readonly verified_at: string | null; }

export interface StrategicPlan extends BusinessAuthorityRef { readonly plan_ref: string; readonly name: string; readonly period: BusinessPeriod | null; readonly lifecycle_state: LifecycleState; readonly objective_refs: readonly string[]; readonly source_refs: readonly BusinessSourceRef[]; }
export interface OperatingPlan extends BusinessAuthorityRef { readonly plan_ref: string; readonly strategic_plan_ref: string | null; readonly name: string; readonly period: BusinessPeriod | null; readonly lifecycle_state: LifecycleState; readonly target_refs: readonly string[]; }
export interface StrategicObjective extends BusinessAuthorityRef { readonly objective_ref: string; readonly plan_ref: string | null; readonly name: string; readonly description: string | null; readonly scope: BusinessScope | null; readonly lifecycle_state: LifecycleState; }
export interface BusinessTarget extends BusinessAuthorityRef { readonly target_ref: string; readonly objective_ref: string | null; readonly name: string; readonly metric_ref: string | null; readonly scope: BusinessScope | null; readonly period: BusinessPeriod | null; readonly lifecycle_state: LifecycleState; readonly performance_state: PerformanceState; }
export interface TargetRelationship { readonly parent_target_ref: string; readonly child_target_ref: string; readonly relationship_type: "CASCADE" | "CONTRIBUTES_TO" | "DEPENDS_ON"; }
export interface KpiDefinition extends MetricDefinition, BusinessAuthorityRef { readonly target_ref: string | null; }
export interface Initiative extends BusinessAuthorityRef { readonly initiative_ref: string; readonly target_refs: readonly string[]; readonly name: string; readonly scope: BusinessScope | null; readonly lifecycle_state: LifecycleState; }
export interface PerformanceReview extends BusinessAuthorityRef { readonly review_ref: string; readonly subject_ref: string; readonly period: BusinessPeriod | null; readonly performance_state: PerformanceState; readonly findings: string | null; readonly evidence_refs: readonly BusinessEvidenceRef[]; readonly lifecycle_state: LifecycleState; }
export interface CorrectiveAction extends BusinessAuthorityRef { readonly action_ref: string; readonly review_ref: string | null; readonly description: string; readonly due_at: string | null; readonly lifecycle_state: LifecycleState; readonly evidence_refs: readonly BusinessEvidenceRef[]; }
export interface TargetRevision extends BusinessAuthorityRef { readonly revision_ref: string; readonly target_ref: string; readonly proposed_observation: MetricObservation | null; readonly reason: string | null; readonly revision_state: RevisionState; readonly evidence_refs: readonly BusinessEvidenceRef[]; }
export interface StrategicSource { readonly source_ref: string; readonly title: string; readonly version: string | null; readonly period: BusinessPeriod | null; readonly owner_role_ref: string | null; readonly readiness: DataReadinessState; readonly evidence_ref: BusinessEvidenceRef | null; }

export interface ReportDefinition extends BusinessAuthorityRef { readonly report_ref: string; readonly name: string; readonly frequency: CadenceFrequency; readonly required_metric_refs: readonly string[]; readonly lifecycle_state: LifecycleState; }
export interface ControlCadenceDefinition { readonly control_id: string; readonly name: string; readonly frequency: CadenceFrequency; readonly owner_role_ref: string | null; readonly reviewer_role_ref: string | null; readonly due_rule: string | null; readonly required_evidence: readonly string[]; readonly status: DataReadinessState; readonly last_submission_at: string | null; }
export interface BusinessProcessStage extends BusinessAuthorityRef { readonly stage_ref: string; readonly name: string; readonly sequence: number; readonly scope: BusinessScope | null; readonly lifecycle_state: LifecycleState; }
export interface BusinessGate extends BusinessAuthorityRef { readonly gate_ref: string; readonly stage_ref: string; readonly name: string; readonly verification_state: VerificationState; readonly evidence_refs: readonly BusinessEvidenceRef[]; }
export interface CrossCheckRequirement { readonly requirement_ref: string; readonly name: string; readonly source_workspace_refs: readonly string[]; readonly reviewer_role_refs: readonly string[]; readonly verification_state: VerificationState; readonly evidence_refs: readonly BusinessEvidenceRef[]; }
