import { authenticatedApiRequest } from "@/lib/api";
import { recordApi } from "@/features/business-records/record-api";
import type {
  SalesCustomerCreateRequest,
  SalesCustomerUpdateRequest,
  SalesCustomerProjection,
  SalesCustomerListProjection,
  SalesCustomerTransitionRequest,
  SalesLeadCreateRequest,
  SalesLeadUpdateRequest,
  SalesLeadProjection,
  SalesLeadListProjection,
  SalesLeadTransitionRequest,
  SalesOpportunityCreateRequest,
  SalesOpportunityUpdateRequest,
  SalesOpportunityProjection,
  SalesOpportunityListProjection,
  SalesOpportunityTransitionRequest,
  SalesSiteVisitCreateRequest,
  SalesSiteVisitUpdateRequest,
  SalesSiteVisitProjection,
  SalesSiteVisitListProjection,
  SalesSiteVisitTransitionRequest,
  SalesBookingCreateRequest,
  SalesBookingUpdateRequest,
  SalesBookingProjection,
  SalesBookingListProjection,
  SalesBookingTransitionRequest,
  SalesClosingCreateRequest,
  SalesClosingUpdateRequest,
  SalesClosingProjection,
  SalesClosingListProjection,
  SalesClosingTransitionRequest,
  SalesFollowupCreateRequest,
  SalesFollowupUpdateRequest,
  SalesFollowupProjection,
  SalesFollowupListProjection,
  SalesFollowupTransitionRequest,
  SalesComplaintCreateRequest,
  SalesComplaintUpdateRequest,
  SalesComplaintProjection,
  SalesComplaintListProjection,
  SalesComplaintTransitionRequest,
  SalesPricingCreateRequest,
  SalesPricingUpdateRequest,
  SalesPricingProjection,
  SalesPricingListProjection,
  SalesPricingTransitionRequest,
  SalesPricingItemCreateRequest,
  SalesPricingItemUpdateRequest,
  SalesPricingItemProjection,
  SalesPricingItemListProjection,
  SalesCollateralCreateRequest,
  SalesCollateralUpdateRequest,
  SalesCollateralProjection,
  SalesCollateralListProjection,
  SalesCollateralTransitionRequest,
  SalesOverview, SalesOpportunityPipelineRequest
} from "@/lib/contracts";

export const salesApi = {
  advancePipeline(identity: string, body: SalesOpportunityPipelineRequest) {
    return authenticatedApiRequest<SalesOpportunityProjection>(`/api/v1/sales/opportunities/${encodeURIComponent(identity)}/pipeline`, { method: "POST", body });
  },
  overview(signal?: AbortSignal) { return authenticatedApiRequest<SalesOverview>("/api/v1/sales/overview", { signal }); },
  customers: recordApi<SalesCustomerCreateRequest, SalesCustomerUpdateRequest, SalesCustomerProjection, SalesCustomerListProjection, SalesCustomerTransitionRequest>("/api/v1/sales/customers"),
  leads: recordApi<SalesLeadCreateRequest, SalesLeadUpdateRequest, SalesLeadProjection, SalesLeadListProjection, SalesLeadTransitionRequest>("/api/v1/sales/leads"),
  opportunities: recordApi<SalesOpportunityCreateRequest, SalesOpportunityUpdateRequest, SalesOpportunityProjection, SalesOpportunityListProjection, SalesOpportunityTransitionRequest>("/api/v1/sales/opportunities"),
  site_visits: recordApi<SalesSiteVisitCreateRequest, SalesSiteVisitUpdateRequest, SalesSiteVisitProjection, SalesSiteVisitListProjection, SalesSiteVisitTransitionRequest>("/api/v1/sales/site-visits"),
  bookings: recordApi<SalesBookingCreateRequest, SalesBookingUpdateRequest, SalesBookingProjection, SalesBookingListProjection, SalesBookingTransitionRequest>("/api/v1/sales/bookings"),
  closings: recordApi<SalesClosingCreateRequest, SalesClosingUpdateRequest, SalesClosingProjection, SalesClosingListProjection, SalesClosingTransitionRequest>("/api/v1/sales/closings"),
  customer_followups: recordApi<SalesFollowupCreateRequest, SalesFollowupUpdateRequest, SalesFollowupProjection, SalesFollowupListProjection, SalesFollowupTransitionRequest>("/api/v1/sales/customer-followups"),
  customer_complaints: recordApi<SalesComplaintCreateRequest, SalesComplaintUpdateRequest, SalesComplaintProjection, SalesComplaintListProjection, SalesComplaintTransitionRequest>("/api/v1/sales/customer-complaints"),
  pricings: recordApi<SalesPricingCreateRequest, SalesPricingUpdateRequest, SalesPricingProjection, SalesPricingListProjection, SalesPricingTransitionRequest>("/api/v1/sales/pricings"),
  pricing_items: recordApi<SalesPricingItemCreateRequest, SalesPricingItemUpdateRequest, SalesPricingItemProjection, SalesPricingItemListProjection, object>("/api/v1/sales/pricing-items"),
  collaterals: recordApi<SalesCollateralCreateRequest, SalesCollateralUpdateRequest, SalesCollateralProjection, SalesCollateralListProjection, SalesCollateralTransitionRequest>("/api/v1/sales/collaterals"),
};
