import { authenticatedApiRequest } from "@/lib/api";
import { recordApi } from "@/features/business-records/record-api";
import type {
  LegalPermitCreateRequest,
  LegalPermitUpdateRequest,
  LegalPermitProjection,
  LegalPermitListProjection,
  LegalPermitTransitionRequest,
  LegalContractCreateRequest,
  LegalContractUpdateRequest,
  LegalContractProjection,
  LegalContractListProjection,
  LegalContractTransitionRequest,
  LegalLandDocumentCreateRequest,
  LegalLandDocumentUpdateRequest,
  LegalLandDocumentProjection,
  LegalLandDocumentListProjection,
  LegalLandDocumentTransitionRequest,
  LegalDueDiligenceCreateRequest,
  LegalDueDiligenceUpdateRequest,
  LegalDueDiligenceProjection,
  LegalDueDiligenceListProjection,
  LegalDueDiligenceTransitionRequest,
  LegalDueDiligenceItemCreateRequest,
  LegalDueDiligenceItemUpdateRequest,
  LegalDueDiligenceItemProjection,
  LegalDueDiligenceItemListProjection,
  LegalDueDiligenceItemTransitionRequest,
  LegalCaseCreateRequest,
  LegalCaseUpdateRequest,
  LegalCaseProjection,
  LegalCaseListProjection,
  LegalCaseTransitionRequest,
  LegalClaimReviewCreateRequest,
  LegalClaimReviewUpdateRequest,
  LegalClaimReviewProjection,
  LegalClaimReviewListProjection,
  LegalClaimReviewTransitionRequest,
  LegalExpiryCreateRequest,
  LegalExpiryUpdateRequest,
  LegalExpiryProjection,
  LegalExpiryListProjection,
  LegalExpiryTransitionRequest,
  LegalPrivacyRequestCreateRequest,
  LegalPrivacyRequestUpdateRequest,
  LegalPrivacyRequestProjection,
  LegalPrivacyRequestListProjection,
  LegalPrivacyRequestTransitionRequest,
  LegalRiskCreateRequest,
  LegalRiskUpdateRequest,
  LegalRiskProjection,
  LegalRiskListProjection,
  LegalRiskTransitionRequest,
  LegalControlCreateRequest,
  LegalControlUpdateRequest,
  LegalControlProjection,
  LegalControlListProjection,
  LegalControlTransitionRequest,
  LegalOverview
} from "@/lib/contracts";

export const legalApi = {
  overview(signal?: AbortSignal) { return authenticatedApiRequest<LegalOverview>("/api/v1/legal/overview", { signal }); },
  permits: recordApi<LegalPermitCreateRequest, LegalPermitUpdateRequest, LegalPermitProjection, LegalPermitListProjection, LegalPermitTransitionRequest>("/api/v1/legal/permits"),
  contracts: recordApi<LegalContractCreateRequest, LegalContractUpdateRequest, LegalContractProjection, LegalContractListProjection, LegalContractTransitionRequest>("/api/v1/legal/contracts"),
  land_documents: recordApi<LegalLandDocumentCreateRequest, LegalLandDocumentUpdateRequest, LegalLandDocumentProjection, LegalLandDocumentListProjection, LegalLandDocumentTransitionRequest>("/api/v1/legal/land-documents"),
  due_diligences: recordApi<LegalDueDiligenceCreateRequest, LegalDueDiligenceUpdateRequest, LegalDueDiligenceProjection, LegalDueDiligenceListProjection, LegalDueDiligenceTransitionRequest>("/api/v1/legal/due-diligences"),
  due_diligence_items: recordApi<LegalDueDiligenceItemCreateRequest, LegalDueDiligenceItemUpdateRequest, LegalDueDiligenceItemProjection, LegalDueDiligenceItemListProjection, LegalDueDiligenceItemTransitionRequest>("/api/v1/legal/due-diligence-items"),
  cases: recordApi<LegalCaseCreateRequest, LegalCaseUpdateRequest, LegalCaseProjection, LegalCaseListProjection, LegalCaseTransitionRequest>("/api/v1/legal/cases"),
  claim_reviews: recordApi<LegalClaimReviewCreateRequest, LegalClaimReviewUpdateRequest, LegalClaimReviewProjection, LegalClaimReviewListProjection, LegalClaimReviewTransitionRequest>("/api/v1/legal/claim-reviews"),
  expiries: recordApi<LegalExpiryCreateRequest, LegalExpiryUpdateRequest, LegalExpiryProjection, LegalExpiryListProjection, LegalExpiryTransitionRequest>("/api/v1/legal/expiries"),
  privacy_requests: recordApi<LegalPrivacyRequestCreateRequest, LegalPrivacyRequestUpdateRequest, LegalPrivacyRequestProjection, LegalPrivacyRequestListProjection, LegalPrivacyRequestTransitionRequest>("/api/v1/legal/privacy-requests"),
  risks: recordApi<LegalRiskCreateRequest, LegalRiskUpdateRequest, LegalRiskProjection, LegalRiskListProjection, LegalRiskTransitionRequest>("/api/v1/legal/risks"),
  controls: recordApi<LegalControlCreateRequest, LegalControlUpdateRequest, LegalControlProjection, LegalControlListProjection, LegalControlTransitionRequest>("/api/v1/legal/controls"),
};
