import { authenticatedApiRequest } from "@/lib/api";
import { recordApi } from "@/features/business-records/record-api";
import type {
  HrEmployeeCreateRequest,
  HrEmployeeUpdateRequest,
  HrEmployeeProjection,
  HrEmployeeListProjection,
  HrEmployeeTransitionRequest,
  HrAttendanceCreateRequest,
  HrAttendanceProjection,
  HrAttendanceListProjection,
  HrLeaveRequestCreateRequest,
  HrLeaveRequestUpdateRequest,
  HrLeaveRequestProjection,
  HrLeaveRequestListProjection,
  HrLeaveRequestTransitionRequest,
  HrRecruitmentCreateRequest,
  HrRecruitmentUpdateRequest,
  HrRecruitmentProjection,
  HrRecruitmentListProjection,
  HrRecruitmentTransitionRequest,
  HrCandidateCreateRequest,
  HrCandidateUpdateRequest,
  HrCandidateProjection,
  HrCandidateListProjection,
  HrCandidateTransitionRequest,
  HrInterviewCreateRequest,
  HrInterviewUpdateRequest,
  HrInterviewProjection,
  HrInterviewListProjection,
  HrInterviewTransitionRequest,
  HrOnboardingCreateRequest,
  HrOnboardingUpdateRequest,
  HrOnboardingProjection,
  HrOnboardingListProjection,
  HrOnboardingTransitionRequest,
  HrPerformanceReviewCreateRequest,
  HrPerformanceReviewUpdateRequest,
  HrPerformanceReviewProjection,
  HrPerformanceReviewListProjection,
  HrPerformanceReviewTransitionRequest,
  HrTrainingCreateRequest,
  HrTrainingUpdateRequest,
  HrTrainingProjection,
  HrTrainingListProjection,
  HrTrainingTransitionRequest,
  HrTrainingEnrollmentCreateRequest,
  HrTrainingEnrollmentProjection,
  HrTrainingEnrollmentListProjection,
  HrTrainingEnrollmentTransitionRequest,
  HrSuccessionCreateRequest,
  HrSuccessionUpdateRequest,
  HrSuccessionProjection,
  HrSuccessionListProjection,
  HrSuccessionTransitionRequest,
  HrSuccessionCandidateCreateRequest,
  HrSuccessionCandidateUpdateRequest,
  HrSuccessionCandidateProjection,
  HrSuccessionCandidateListProjection,
  HrGrievanceCreateRequest,
  HrGrievanceUpdateRequest,
  HrGrievanceProjection,
  HrGrievanceListProjection,
  HrGrievanceTransitionRequest,
  HrEmploymentContractCreateRequest,
  HrEmploymentContractUpdateRequest,
  HrEmploymentContractProjection,
  HrEmploymentContractListProjection,
  HrEmploymentContractTransitionRequest,
  HrPersonnelFileCreateRequest,
  HrPersonnelFileUpdateRequest,
  HrPersonnelFileProjection,
  HrPersonnelFileListProjection,
  HrPersonnelFileTransitionRequest,
  HrOverview
} from "@/lib/contracts";

export const hrApi = {
  overview(signal?: AbortSignal) { return authenticatedApiRequest<HrOverview>("/api/v1/hr/overview", { signal }); },
  employees: recordApi<HrEmployeeCreateRequest, HrEmployeeUpdateRequest, HrEmployeeProjection, HrEmployeeListProjection, HrEmployeeTransitionRequest>("/api/v1/hr/employees"),
  attendances: recordApi<HrAttendanceCreateRequest, object, HrAttendanceProjection, HrAttendanceListProjection, object>("/api/v1/hr/attendances"),
  leave_requests: recordApi<HrLeaveRequestCreateRequest, HrLeaveRequestUpdateRequest, HrLeaveRequestProjection, HrLeaveRequestListProjection, HrLeaveRequestTransitionRequest>("/api/v1/hr/leave-requests"),
  recruitments: recordApi<HrRecruitmentCreateRequest, HrRecruitmentUpdateRequest, HrRecruitmentProjection, HrRecruitmentListProjection, HrRecruitmentTransitionRequest>("/api/v1/hr/recruitments"),
  candidates: recordApi<HrCandidateCreateRequest, HrCandidateUpdateRequest, HrCandidateProjection, HrCandidateListProjection, HrCandidateTransitionRequest>("/api/v1/hr/candidates"),
  interviews: recordApi<HrInterviewCreateRequest, HrInterviewUpdateRequest, HrInterviewProjection, HrInterviewListProjection, HrInterviewTransitionRequest>("/api/v1/hr/interviews"),
  onboardings: recordApi<HrOnboardingCreateRequest, HrOnboardingUpdateRequest, HrOnboardingProjection, HrOnboardingListProjection, HrOnboardingTransitionRequest>("/api/v1/hr/onboardings"),
  performance_reviews: recordApi<HrPerformanceReviewCreateRequest, HrPerformanceReviewUpdateRequest, HrPerformanceReviewProjection, HrPerformanceReviewListProjection, HrPerformanceReviewTransitionRequest>("/api/v1/hr/performance-reviews"),
  trainings: recordApi<HrTrainingCreateRequest, HrTrainingUpdateRequest, HrTrainingProjection, HrTrainingListProjection, HrTrainingTransitionRequest>("/api/v1/hr/trainings"),
  training_enrollments: recordApi<HrTrainingEnrollmentCreateRequest, object, HrTrainingEnrollmentProjection, HrTrainingEnrollmentListProjection, HrTrainingEnrollmentTransitionRequest>("/api/v1/hr/training-enrollments"),
  successions: recordApi<HrSuccessionCreateRequest, HrSuccessionUpdateRequest, HrSuccessionProjection, HrSuccessionListProjection, HrSuccessionTransitionRequest>("/api/v1/hr/successions"),
  succession_candidates: recordApi<HrSuccessionCandidateCreateRequest, HrSuccessionCandidateUpdateRequest, HrSuccessionCandidateProjection, HrSuccessionCandidateListProjection, object>("/api/v1/hr/succession-candidates"),
  grievances: recordApi<HrGrievanceCreateRequest, HrGrievanceUpdateRequest, HrGrievanceProjection, HrGrievanceListProjection, HrGrievanceTransitionRequest>("/api/v1/hr/grievances"),
  employment_contracts: recordApi<HrEmploymentContractCreateRequest, HrEmploymentContractUpdateRequest, HrEmploymentContractProjection, HrEmploymentContractListProjection, HrEmploymentContractTransitionRequest>("/api/v1/hr/employment-contracts"),
  personnel_files: recordApi<HrPersonnelFileCreateRequest, HrPersonnelFileUpdateRequest, HrPersonnelFileProjection, HrPersonnelFileListProjection, HrPersonnelFileTransitionRequest>("/api/v1/hr/personnel-files"),
};
