"use client";

import { useEffect, useState } from "react";
import { Button, DataTable, Metric, PageHeader, Section, Tabs, type DataTableColumn, type TabItem } from "@/components/ui";
import type { BusinessTarget } from "@/lib/contracts";
import type { SessionProjection } from "@/features/session";
import { strategyApi } from "@/modules/strategy";
import { HrDataPage, type HrTab } from "./shared/hr-data-page";
import { HrLayout } from "./hr-layout";
import { HrExtractionDrawer, HrSourceStateView, HrSourceStrip, HrStatusDrawer, HrUnavailableFormDrawer, type HrFormField } from "./shared/hr-ui";
import styles from "./hr.module.css";

type HrRow = { readonly id: string; readonly first: string; readonly second: string; readonly third: string; readonly fourth: string; readonly status: string };
type ModuleKey = "organization" | "recruitment" | "onboarding" | "employees" | "attendance" | "peoplePerformance" | "compensation" | "compliance" | "offboarding" | "ga";
type ModuleTab = { readonly label: string; readonly headers: readonly string[]; readonly emptyDescription: string; readonly action?: string; readonly fields?: readonly HrFormField[]; readonly extraction?: boolean; readonly secondaryAction?: string; readonly secondaryFields?: readonly HrFormField[] };
type ModuleConfig = { readonly title: string; readonly eyebrow: string; readonly description: string; readonly tabs: readonly ModuleTab[] };

function columnsFor(headers: readonly string[]): readonly DataTableColumn<HrRow>[] {
  const keys: readonly (keyof HrRow)[] = ["first", "second", "third", "fourth", "status"];
  return headers.map((header, index) => { const valueKey = keys[index] ?? "status"; return { header, key: `column-${index}`, render: (row: HrRow) => row[valueKey] }; });
}
const noRows: readonly HrRow[] = [];
function tab(label: string, headers: readonly string[], emptyDescription: string, action?: string, fields?: readonly HrFormField[], extraction = false, secondaryAction?: string, secondaryFields?: readonly HrFormField[]): ModuleTab { return { action, emptyDescription, extraction, fields, headers, label, secondaryAction, secondaryFields }; }
const relation = (label: string, name: string, required = false): HrFormField => ({ label, name, relation: true, required });
const select = (label: string, name: string, required = false): HrFormField => ({ label, name, select: true, required });
const text = (label: string, name: string, required = false, type: HrFormField["type"] = "text"): HrFormField => ({ label, name, required, type });

const forms = {
  position: [text("Nama Posisi", "position", true), relation("Divisi", "division", true), relation("Melapor Kepada", "reports_to"), select("Jenis Peran", "role_type"), select("Jenis Kepegawaian", "employment_type"), text("Kebutuhan Headcount", "headcount_need", false, "number"), text("Deskripsi", "description", false, "textarea"), text("Persyaratan", "requirements", false, "textarea")],
  vacancy: [relation("Posisi", "position", true), relation("Divisi", "division", true), relation("Penanggung Jawab Rekrutmen", "hiring_owner", true), relation("Hiring Manager", "hiring_manager"), text("Kebutuhan Headcount", "headcount", true, "number"), select("Jenis Kepegawaian", "employment_type"), text("Alasan", "reason", true, "textarea"), text("Target Isi", "target_fill_date", false, "date"), text("Persyaratan", "requirements", false, "textarea"), text("Deskripsi", "description", false, "textarea"), relation("Rentang Kompensasi", "compensation_range"), select("Kebutuhan Persetujuan", "approval_requirement")],
  candidate: [text("Nama", "name", true), text("Kontak", "contact", true), text("Email", "email"), relation("Posisi", "position", true), select("Sumber", "source"), relation("CV", "cv", true), text("Portfolio", "portfolio"), text("Ketersediaan", "availability"), text("Catatan", "notes", false, "textarea")],
  employeeCreate: [relation("Kandidat / Identitas Terpilih", "candidate", true), relation("Posisi", "position", true), relation("Divisi", "division", true), select("Jenis Kepegawaian", "employment_type", true), text("Tanggal Mulai", "start_date", true, "date"), relation("Dokumen", "documents")],
  interview: [relation("Kandidat", "candidate", true), select("Jenis Interview", "interview_type", true), text("Tanggal & Waktu", "date_time", true, "datetime-local"), relation("Interviewer", "interviewer", true), text("Lokasi / Media", "location_medium"), relation("Template Penilaian", "assessment_template"), text("Catatan", "notes", false, "textarea")],
  offer: [relation("Kandidat", "candidate", true), relation("Posisi", "position", true), select("Jenis Kepegawaian", "employment_type"), text("Tanggal Mulai yang Diusulkan", "proposed_start_date", false, "date"), relation("Paket Kompensasi", "compensation_package"), text("Benefit", "benefits", false, "textarea"), relation("Referensi Kontrak", "contract_ref"), text("Catatan", "notes", false, "textarea")],
  onboarding: [relation("Karyawan", "employee", true), relation("Posisi", "position"), relation("Divisi", "division"), text("Tanggal Mulai", "start_date", true, "date"), relation("Pendamping", "buddy"), text("Catatan", "notes", false, "textarea")],
  probation: [relation("Karyawan", "employee", true), text("Tanggal Mulai", "start_date", true, "date"), text("Perkiraan Selesai", "expected_end", false, "date"), relation("Peninjau", "reviewer"), text("Review Jatuh Tempo", "review_due", false, "date"), text("Catatan", "notes", false, "textarea")],
  employmentChange: [relation("Karyawan", "employee", true), select("Jenis Perubahan", "change_type", true), text("Tanggal Berlaku", "effective_date", true, "date"), text("Status Lama", "old_state"), select("Status Baru", "new_state", true), text("Alasan", "reason", true, "textarea"), text("Bukti Pendukung", "evidence", false, "textarea")],
  attendanceCorrection: [relation("Karyawan", "employee", true), text("Tanggal Kehadiran", "attendance_date", true, "date"), text("Alasan", "reason", true, "textarea"), text("Bukti Pendukung", "evidence", true, "textarea"), relation("Peninjau", "reviewer", true)],
  leave: [relation("Karyawan", "employee", true), select("Jenis Cuti", "leave_type", true), text("Mulai", "starts_at", true, "date"), text("Selesai", "ends_at", true, "date"), text("Alasan", "reason", false, "textarea"), text("Bukti Pendukung", "evidence", false, "textarea"), text("Serah Terima", "handover", false, "textarea")],
  review: [relation("Karyawan", "employee", true), relation("Periode", "period", true), relation("Peninjau", "reviewer", true), text("Sasaran", "goals", false, "textarea"), text("Hasil", "results", false, "textarea"), text("Kompetensi", "competency", false, "textarea"), text("Umpan Balik", "feedback", false, "textarea"), text("Rencana Pengembangan", "development_plan", false, "textarea")],
  compensation: [relation("Karyawan", "employee", true), select("Jenis Perubahan", "change_type", true), text("Tanggal Berlaku", "effective_date", true, "date"), relation("Bukti Pendukung", "evidence"), text("Catatan", "notes", false, "textarea")],
  compliance: [relation("Karyawan / Objek", "subject", true), select("Jenis Persyaratan", "requirement_type", true), relation("Dokumen Pendukung", "document"), text("Tenggat", "deadline", false, "date"), text("Catatan", "notes", false, "textarea")],
  offboarding: [relation("Karyawan", "employee", true), text("Alasan", "reason", true, "textarea"), text("Tanggal Kerja Terakhir", "last_working_date", true, "date"), relation("Manager", "manager", true), text("Serah Terima Pengetahuan", "knowledge_transfer"), relation("Pengembalian Aset", "asset_return"), relation("Pencabutan Akses", "access_revocation"), relation("Dokumen Akhir", "final_documents"), relation("Penyelesaian Finance", "finance_settlement"), text("Catatan", "notes", false, "textarea")],
  ga: [relation("Pemohon", "requester", true), select("Jenis Fasilitas", "facility_type", true), relation("Lokasi", "location"), text("Kebutuhan", "need", false, "textarea")],
} satisfies Record<string, readonly HrFormField[]>;

const moduleConfig: Record<ModuleKey, ModuleConfig> = {
  organization: { title: "Organisasi & Tenaga Kerja", eyebrow: "PUSAT SDM", description: "Pantau struktur organisasi, kebutuhan tenaga kerja, dan kapasitas tanpa menyimpulkan data yang belum tersedia.", tabs: [tab("Struktur", ["Unit", "Posisi", "Karyawan", "Status"], "Hierarki organisasi belum tersedia.", "Siapkan Posisi", forms.position), tab("Divisi", ["Divisi", "Headcount", "Posisi Terbuka", "Penanggung Jawab", "Status Data"], "Data divisi belum tersedia."), tab("Posisi", ["Posisi", "Divisi", "Jenis Peran", "Kebutuhan Headcount", "Status"], "Data posisi belum tersedia.", "Siapkan Posisi", forms.position), tab("Headcount", ["Divisi", "Posisi Disetujui", "Terisi", "Kosong", "Onboarding", "Akan Keluar", "Kapasitas"], "Data headcount belum tersedia."), tab("Kebutuhan Tenaga Kerja", ["Divisi", "Posisi", "Kebutuhan", "Alasan", "Tenggat", "Status"], "Kebutuhan tenaga kerja belum tersedia."), tab("Riwayat", ["Perubahan", "Objek", "Tanggal Berlaku", "Penanggung Jawab", "Status"], "Riwayat organisasi belum tersedia.")] },
  recruitment: { title: "Rekrutmen & Kandidat", eyebrow: "TALENTA", description: "Kelola kesiapan proses rekrutmen tanpa menyimpulkan keputusan kandidat yang belum tersedia.", tabs: [tab("Posisi Terbuka", ["Posisi", "Divisi", "Penanggung Jawab Rekrutmen", "Kebutuhan", "Kandidat", "Tahap", "Target Isi", "Status"], "Posisi terbuka belum tersedia.", "Siapkan Lowongan", forms.vacancy), tab("Kandidat", ["Kandidat", "Posisi", "Tahap", "Penanggung Jawab", "Sumber", "Aktivitas Terakhir", "Tindakan Berikutnya", "Status"], "Kandidat belum tersedia.", "Tambah Kandidat", forms.candidate, true), tab("Interview", ["Kandidat", "Jenis", "Jadwal", "Pewawancara", "Penilaian", "Status"], "Jadwal interview belum tersedia.", "Jadwalkan Interview", forms.interview), tab("Offer", ["Kandidat", "Posisi", "Tanggal Mulai", "Paket Kompensasi", "Persetujuan", "Status"], "Offer belum tersedia.", "Siapkan Offer", forms.offer), tab("Ditutup", ["Posisi", "Kandidat", "Alasan", "Tanggal", "Status"], "Rekrutmen ditutup belum tersedia."), tab("Riwayat", ["Objek", "Perubahan", "Tanggal", "Penanggung Jawab", "Status"], "Riwayat rekrutmen belum tersedia.")] },
  onboarding: { title: "Onboarding & Masa Percobaan", eyebrow: "TALENTA", description: "Pantau checklist onboarding, akses, peralatan, orientasi, dan masa percobaan dari sumber resmi.", tabs: [tab("Onboarding", ["Karyawan", "Posisi", "Divisi", "Tanggal Mulai", "Dokumen", "Peralatan", "Akses", "Orientasi", "Penanggung Jawab", "Progres", "Status"], "Data onboarding belum tersedia.", "Mulai Onboarding", forms.onboarding), tab("Dokumen", ["Karyawan", "Dokumen", "Persyaratan", "Verifikasi", "Status"], "Dokumen onboarding belum tersedia.", "Telaah Dokumen", forms.onboarding, true), tab("Akses", ["Karyawan", "Akses Dibutuhkan", "IT/Identity", "Status", "Tanggal"], "Status akses onboarding belum tersedia."), tab("Peralatan", ["Karyawan", "Peralatan", "GA/IT", "Serah Terima", "Status"], "Status peralatan onboarding belum tersedia."), tab("Orientasi", ["Karyawan", "Materi", "Jadwal", "Penanggung Jawab", "Status"], "Data orientasi belum tersedia."), tab("Masa Percobaan", ["Karyawan", "Mulai", "Perkiraan Selesai", "Peninjau", "Review Jatuh Tempo", "Status", "Hasil"], "Data masa percobaan belum tersedia.", "Catat Masa Percobaan", forms.probation), tab("Riwayat", ["Karyawan", "Perubahan", "Tanggal", "Penanggung Jawab", "Status"], "Riwayat onboarding belum tersedia.")] },
  employees: { title: "Karyawan", eyebrow: "TALENTA", description: "Data karyawan ditampilkan sesuai kewenangan dan klasifikasi informasi yang berlaku.", tabs: [tab("Aktif", ["Nama", "Employee ID", "Position", "Division", "Manager", "Employment Type", "Join Date", "Employment Status", "Contract End", "Status"], "Karyawan aktif belum tersedia."), tab("Probation", ["Nama", "Position", "Start", "Expected End", "Reviewer", "Status"], "Karyawan masa percobaan belum tersedia."), tab("Cuti Panjang", ["Nama", "Division", "Periode", "Penanggung Jawab", "Status"], "Data cuti panjang belum tersedia."), tab("Akan Berakhir", ["Nama", "Position", "Contract End", "Penanggung Jawab", "Status"], "Kontrak mendekati akhir belum tersedia."), tab("Offboarding", ["Nama", "Manager", "Tanggal Kerja Terakhir", "Checklist", "Status"], "Offboarding karyawan belum tersedia."), tab("Tidak Aktif", ["Nama", "Employee ID", "Position", "Division", "Employment Status", "Status"], "Karyawan tidak aktif belum tersedia."), tab("Semua", ["Nama", "Employee ID", "Position", "Division", "Manager", "Employment Type", "Join Date", "Employment Status", "Contract End", "Status"], "Data karyawan belum tersedia.", "Siapkan Karyawan", forms.employeeCreate, false, "Catat Perubahan", forms.employmentChange)] },
  attendance: { title: "Kehadiran & Cuti", eyebrow: "OPERASIONAL SDM", description: "Pantau kehadiran, cuti, izin, lembur, dan anomali tanpa menghitung saldo atau mengganti event asli.", tabs: [tab("Kehadiran", ["Employee", "Date", "Schedule", "Check In", "Check Out", "Attendance State", "Source", "Verification"], "Data kehadiran belum tersedia."), tab("Cuti", ["Employee", "Leave Type", "Start", "End", "Handover", "Status"], "Data cuti belum tersedia.", "Ajukan Cuti", forms.leave), tab("Izin", ["Employee", "Jenis Izin", "Periode", "Bukti", "Peninjau", "Status"], "Data izin belum tersedia."), tab("Lembur", ["Employee", "Date", "Schedule", "Evidence", "Finance/Payroll", "Status"], "Data lembur belum tersedia."), tab("Anomali", ["Employee", "Tanggal", "Anomali", "Alasan", "Peninjau", "Status"], "Anomali kehadiran belum tersedia.", "Ajukan Koreksi", forms.attendanceCorrection), tab("Riwayat", ["Employee", "Event", "Perubahan", "Tanggal", "Peninjau", "Status"], "Riwayat kehadiran belum tersedia.")] },
  peoplePerformance: { title: "Kinerja & Pengembangan", eyebrow: "OPERASIONAL SDM", description: "Ruang kerja review dan pengembangan karyawan; penilaian akhir tetap membutuhkan peninjau manusia.", tabs: [tab("Review", ["Employee", "Period", "Reviewer", "Goals", "Feedback", "Status"], "Review kinerja belum tersedia.", "Siapkan Review", forms.review), tab("Sasaran Individu", ["Employee", "Sasaran", "Periode", "Peninjau", "Status"], "Sasaran individu belum tersedia."), tab("Kompetensi", ["Employee", "Kompetensi", "Evidence", "Reviewer", "Status"], "Data kompetensi belum tersedia."), tab("Pengembangan", ["Need", "Action", "Owner", "Target Date", "Evidence", "Status"], "Rencana pengembangan belum tersedia."), tab("Pelatihan", ["Training", "Employee", "Skill / Requirement", "Schedule", "Result", "Evidence", "Status"], "Data pelatihan belum tersedia."), tab("Riwayat", ["Employee", "Review", "Perubahan", "Tanggal", "Reviewer", "Status"], "Riwayat pengembangan belum tersedia.")] },
  compensation: { title: "Kompensasi & Benefit", eyebrow: "OPERASIONAL SDM", description: "Siapkan entitlement dan benefit tanpa membuka informasi sensitif atau menyimpulkan pembayaran Finance.", tabs: [tab("Kompensasi", ["Employee", "Jenis", "Periode", "Status Sumber", "Status"], "Data kompensasi belum tersedia."), tab("Benefit", ["Employee", "Benefit", "Periode", "Kelayakan", "Status"], "Data benefit belum tersedia."), tab("Persiapan Payroll", ["Period", "Employee Entitlement", "Allowance", "Deduction Instruction", "Attendance Impact", "Overtime Impact", "Leave Impact", "Status"], "Persiapan payroll belum tersedia."), tab("Perubahan", ["Employee", "Perubahan", "Tanggal Berlaku", "Versi", "Peninjau", "Status"], "Perubahan kompensasi belum tersedia.", "Ajukan Perubahan", forms.compensation), tab("Riwayat", ["Employee", "Perubahan", "Tanggal", "Versi", "Status"], "Riwayat kompensasi belum tersedia.")] },
  compliance: { title: "Dokumen & Kepatuhan", eyebrow: "OPERASIONAL SDM", description: "Pantau persyaratan dokumen dan kepatuhan tanpa menyimpulkan kelengkapan atau validitas legal.", tabs: [tab("Persyaratan Dokumen", ["Employee", "Requirement", "Tenggat", "Sumber", "Status"], "Persyaratan dokumen belum tersedia.", "Tambah Persyaratan", forms.compliance, true), tab("Review Dokumen", ["Employee", "Dokumen", "Reviewer", "Verification", "Status"], "Review dokumen belum tersedia.", "Telaah Dokumen", forms.compliance, true), tab("Verifikasi", ["Dokumen", "Reviewer", "Evidence", "Tanggal", "Status"], "Verifikasi dokumen belum tersedia."), tab("Policy Acknowledgement", ["Employee", "Policy", "Tanggal", "Bukti", "Status"], "Acknowledgement kebijakan belum tersedia."), tab("Mandatory Training", ["Employee", "Training", "Requirement", "Tenggat", "Status"], "Persyaratan pelatihan wajib belum tersedia."), tab("HR Case", ["Subjek", "Kategori", "Penanggung Jawab", "Klasifikasi", "Status"], "Data HR case tidak tersedia tanpa kewenangan yang sesuai.")] },
  offboarding: { title: "Perubahan & Offboarding", eyebrow: "OPERASIONAL SDM", description: "Pantau kesiapan offboarding lintas HR, IT, GA, Finance, dan Legal tanpa mengambil alih kewenangan mereka.", tabs: [tab("Berjalan", ["Employee", "Reason", "Last Working Date", "Manager", "Checklist", "Status"], "Offboarding berjalan belum tersedia.", "Mulai Offboarding", forms.offboarding, true), tab("Perubahan", ["Employee", "Change Type", "Effective Date", "Reason", "Approval", "Status"], "Perubahan pekerjaan belum tersedia.", "Catat Perubahan", forms.employmentChange), tab("Checklist", ["Employee", "Knowledge Transfer", "Asset Return", "Access Revocation", "Final Documents", "Status"], "Checklist offboarding belum tersedia."), tab("Selesai", ["Employee", "Last Working Date", "Dokumen", "Penyelesaian Finance", "Status"], "Offboarding selesai belum tersedia."), tab("Riwayat", ["Employee", "Perubahan", "Tanggal", "Peninjau", "Status"], "Riwayat offboarding belum tersedia.")] },
  ga: { title: "GA & Fasilitas", eyebrow: "GA", description: "Pantau fasilitas dan layanan umum dalam scope GA tanpa membangun sistem aset atau purchasing baru.", tabs: [tab("Fasilitas", ["Office Facility", "Lokasi", "Penanggung Jawab", "Kondisi", "Status"], "Data fasilitas belum tersedia.", "Ajukan Permintaan", forms.ga), tab("Permintaan", ["Permintaan", "Pemohon", "Lokasi", "Owner", "Status"], "Permintaan fasilitas belum tersedia.", "Ajukan Permintaan", forms.ga), tab("Inventaris", ["GA Asset", "Lokasi", "Penanggung Jawab", "Status", "Sumber"], "Inventaris GA belum tersedia."), tab("Pemeliharaan", ["Fasilitas", "Vendor", "Jadwal", "Evidence", "Status"], "Pemeliharaan fasilitas belum tersedia."), tab("Riwayat", ["Objek", "Perubahan", "Tanggal", "Penanggung Jawab", "Status"], "Riwayat fasilitas belum tersedia.")] },
};

function ReadinessAction({ action, extraction, fields, secondaryAction, secondaryFields }: Readonly<{ action: string; extraction?: boolean; fields?: readonly HrFormField[]; secondaryAction?: string; secondaryFields?: readonly HrFormField[] }>) {
  const [open, setOpen] = useState(false);
  const [extractionOpen, setExtractionOpen] = useState(false);
  return <div>{fields ? <><Button onClick={() => setOpen(true)} size="sm" variant="secondary">{action}</Button><HrUnavailableFormDrawer description="Form ini menyiapkan struktur kerja. Pilihan sumber dan penyimpanan belum tersedia." fields={fields} onClose={() => setOpen(false)} open={open} title={action} /></> : null}{secondaryFields && secondaryAction ? <SecondaryReadinessAction action={secondaryAction} fields={secondaryFields} /> : null}{extraction ? <><Button onClick={() => setExtractionOpen(true)} size="sm" variant="ghost">Ambil/Telaah dari Dokumen</Button><HrExtractionDrawer onClose={() => setExtractionOpen(false)} open={extractionOpen} /></> : null}</div>;
}
function SecondaryReadinessAction({ action, fields }: Readonly<{ action: string; fields: readonly HrFormField[] }>) { const [open, setOpen] = useState(false); return <><Button onClick={() => setOpen(true)} size="sm" variant="ghost">{action}</Button><HrUnavailableFormDrawer description="Perubahan disiapkan sebagai readiness. Penyimpanan belum tersedia." fields={fields} onClose={() => setOpen(false)} open={open} title={action} /></>; }

export function HrModulePage({ module, workspaceKey }: Readonly<{ module: ModuleKey; workspaceKey?: string }>) {
  const config = moduleConfig[module];
  const tabs: readonly HrTab<HrRow>[] = config.tabs.map((definition) => ({ id: definition.label, label: definition.label, title: `${config.title} — ${definition.label}`, description: config.description, caption: `${definition.label} ${config.title}`, columns: columnsFor(definition.headers), emptyDescription: definition.emptyDescription, rows: noRows, state: "unavailable", actions: definition.action || definition.extraction ? <ReadinessAction action={definition.action ?? ""} extraction={definition.extraction} fields={definition.fields} secondaryAction={definition.secondaryAction} secondaryFields={definition.secondaryFields} /> : undefined }));
  return <HrDataPage description={config.description} eyebrow={config.eyebrow} tabs={tabs} title={config.title} workspaceKey={workspaceKey} requireGa={module === "ga"} />;
}

export function HrSummaryPage({ workspaceKey }: Readonly<{ workspaceKey?: string }>) { return <HrLayout workspaceKey={workspaceKey}>{(session) => <HrSummary session={session} />}</HrLayout>; }
function HrSummary({ session }: Readonly<{ session: SessionProjection }>) {
  const [statusOpen, setStatusOpen] = useState(false);
  const workspace = session.principal && "actor" in session.principal ? session.principal.active_workspace?.workspace : null;
  const isGa = workspace?.division_code?.toUpperCase() === "HR_GA" || workspace?.division_code?.toUpperCase() === "HRGA";
  const base = workspace ? `/workspace/${encodeURIComponent(workspace.workspace_key)}` : "/workspace";
  const metrics = ["Karyawan Aktif", "Posisi Terbuka", "Kandidat Aktif", "Onboarding Berjalan", "Kontrak Mendekati Tenggat", "Cuti Menunggu"];
  const secondary = ["Masa Percobaan", "Dokumen Tidak Lengkap", "Review Kinerja Menunggu", "Offboarding Berjalan"];
  return <div className={styles.page}><PageHeader description="Ringkasan tenaga kerja, talenta, kehadiran, pengembangan, dan kesiapan operasional SDM." eyebrow={isGa ? "HR / GA" : "HR"} metadata={`Workspace aktif: ${workspace?.workspace_name ?? "—"}`} title={isGa ? "HR / GA" : "HR"} /><div className={styles.contextBar}><ContextItem label="Periode" value="—" /><ContextItem label="Workspace" value={workspace?.workspace_name ?? "—"} /><ContextItem label="Status Data" value="Belum Terhubung" /><ContextItem label="Pembaruan Terverifikasi Terakhir" value="—" /></div><HrSourceStrip onStatus={() => setStatusOpen(true)} /><section aria-label="Indikator utama SDM" className={styles.metricGrid}>{metrics.map((label) => <Metric key={label} label={label} status="Belum Terhubung" value="—" />)}</section><Section title="Indikator Operasional"><DataTable caption="Indikator operasional SDM" columns={summaryColumns} rows={secondary.map((item) => ({ id: item, first: item, second: "—", third: "—", fourth: "—", status: "Belum Terhubung" }))} /></Section><SummaryReadiness title="Ringkasan Tenaga Kerja" headers={["Divisi", "Headcount", "Posisi Terbuka", "Karyawan Masuk", "Karyawan Keluar", "Status Data"]} description="Ringkasan tenaga kerja belum tersedia." /><SummaryReadiness title="Perhatian Rekrutmen" headers={["Posisi", "Kandidat", "Tahap", "Penanggung Jawab", "Tindakan Berikutnya", "Tenggat"]} description="Perhatian rekrutmen belum tersedia." /><SummaryReadiness title="Perhatian Hubungan Kerja" headers={["Jenis Perhatian", "Karyawan", "Tenggat", "Penanggung Jawab", "Status"]} description="Perhatian hubungan kerja belum tersedia." /><div className={styles.summaryGrid}><Section title="Persetujuan SDM" actions={<a href={`${base}/approvals`}>Lihat Semua Persetujuan</a>}><HrSourceStateView description="Persetujuan SDM belum tersedia." state="unavailable" /></Section><Section title="Status Dokumen & Kepatuhan"><HrSourceStateView description="Status dokumen dan kepatuhan belum tersedia." state="unavailable" /></Section></div><HrStatusDrawer onClose={() => setStatusOpen(false)} open={statusOpen} /></div>;
}
const summaryColumns: readonly DataTableColumn<HrRow>[] = [{ header: "Indikator", key: "first", render: (row) => row.first }, { header: "Nilai", key: "second", render: (row) => row.second }, { header: "Status Data", key: "status", render: (row) => row.status }];
function SummaryReadiness({ description, headers, title }: Readonly<{ description: string; headers: readonly string[]; title: string }>) { return <Section title={title}><DataTable caption={title} columns={columnsFor(headers)} emptyState={<HrSourceStateView description={description} state="unavailable" />} rows={noRows} /></Section>; }
function ContextItem({ label, value }: Readonly<{ label: string; value: string }>) { return <div className={styles.contextItem}><span className={styles.contextLabel}>{label}</span><span className={styles.contextValue}>{value}</span></div>; }

export function HrPerformancePage({ workspaceKey }: Readonly<{ workspaceKey?: string }>) { return <HrLayout workspaceKey={workspaceKey}>{(session) => <HrPerformance session={session} />}</HrLayout>; }
function HrPerformance({ session }: Readonly<{ session: SessionProjection }>) {
  const [activeTab, setActiveTab] = useState("Ringkasan");
  const [targets, setTargets] = useState<readonly BusinessTarget[]>([]);
  const [strategyState, setStrategyState] = useState<"loading" | "error" | "connected-empty" | "connected-data">("loading");
  const workspace = session.principal && "actor" in session.principal ? session.principal.active_workspace?.workspace : null;
  const tabs: readonly TabItem[] = ["Ringkasan", "Target", "KPI", "Rekrutmen", "Tenaga Kerja", "Kehadiran", "Pengembangan", "Riwayat"].map((label) => ({ id: label, label }));
  useEffect(() => { let cancelled = false; void strategyApi.listTargets().then((nextTargets) => { if (cancelled) return; setTargets(nextTargets); setStrategyState(nextTargets.length === 0 ? "connected-empty" : "connected-data"); }).catch(() => { if (!cancelled) setStrategyState("error"); }); return () => { cancelled = true; }; }, []);
  const targetRows = targets.filter((target) => target.observations?.some((observation) => observation.kind === "TARGET")).map((target) => ({ id: target.target_id, first: target.name, second: formatHrPeriod(target.period), third: targetValue(target), fourth: "—", status: "Belum Dinilai" }));
  const content = activeTab === "Ringkasan" || activeTab === "Target" ? strategyState === "connected-data" ? <DataTable caption="Target Strategi untuk SDM" columns={performanceColumns} rows={targetRows} /> : <HrSourceStateView description={strategyState === "error" ? "Data Strategi belum dapat dimuat." : strategyState === "connected-empty" ? "Belum ada target Strategi." : "Target Strategi sedang dimuat."} state={strategyState} /> : <HrSourceStateView description={`Data ${activeTab} SDM belum tersedia.`} state="unavailable" />;
  return <div className={styles.page}><PageHeader description="Target SDM berasal dari Strategi. Aktual dan perkiraan HR tetap terpisah sampai sumber resmi tersedia." eyebrow="KINERJA" metadata={`Workspace aktif: ${workspace?.workspace_name ?? "—"}`} title={`Target & Kinerja${activeTab === "Ringkasan" ? "" : ` — ${activeTab}`}`} /><HrSourceStrip sources={["strategy", "employees", "performance"]} statuses={{ strategy: strategyState, employees: "unavailable", performance: "unavailable" }} /><Tabs ariaLabel="Navigasi target dan kinerja SDM" items={tabs} onValueChange={setActiveTab} value={activeTab} /><Section description="Target tidak sama dengan aktual atau perkiraan." title={activeTab}>{content}</Section><Section title="Aktual dan Perkiraan SDM"><HrSourceStateView description="Data aktual dan perkiraan SDM belum tersedia." state="unavailable" /></Section></div>;
}
const performanceColumns: readonly DataTableColumn<HrRow>[] = [{ header: "Target", key: "first", render: (row) => row.first }, { header: "Periode", key: "second", render: (row) => row.second }, { header: "Nilai Target", key: "third", render: (row) => row.third }, { header: "Aktual HR", key: "fourth", render: (row) => row.fourth }, { header: "Status", key: "status", render: (row) => row.status }];
function formatHrPeriod(period: BusinessTarget["period"] | null | undefined): string { if (!period) return "—"; if (period.label?.trim()) return period.label; const startsAt = new Date(period.starts_at); const endsAt = new Date(period.ends_at); if (Number.isNaN(startsAt.valueOf()) || Number.isNaN(endsAt.valueOf())) return "Belum Dinilai"; const formatter = new Intl.DateTimeFormat("id-ID", { dateStyle: "medium" }); return `${formatter.format(startsAt)} – ${formatter.format(endsAt)}`; }
function targetValue(target: BusinessTarget): string { const observation = target.observations?.find((candidate) => candidate.kind === "TARGET"); if (observation?.value === null || observation?.value === undefined) return "—"; if (typeof observation.value === "number") return new Intl.NumberFormat("id-ID", { maximumFractionDigits: 2 }).format(observation.value); if (typeof observation.value === "boolean") return observation.value ? "Ya" : "Tidak"; return String(observation.value); }
