import { authenticatedApiRequest } from "@/lib/api";
import { recordApi } from "@/features/business-records/record-api";
import type {
  PropertyUnitCreateRequest,
  PropertyUnitUpdateRequest,
  PropertyUnitProjection,
  PropertyUnitListProjection,
  PropertyUnitTransitionRequest,
  PropertyMilestoneCreateRequest,
  PropertyMilestoneUpdateRequest,
  PropertyMilestoneProjection,
  PropertyMilestoneListProjection,
  PropertyMilestoneTransitionRequest,
  PropertyConstructionPackageCreateRequest,
  PropertyConstructionPackageUpdateRequest,
  PropertyConstructionPackageProjection,
  PropertyConstructionPackageListProjection,
  PropertyConstructionPackageTransitionRequest,
  PropertyConstructionUpdateCreateRequest,
  PropertyConstructionUpdateUpdateRequest,
  PropertyConstructionUpdateProjection,
  PropertyConstructionUpdateListProjection,
  PropertyConstructionUpdateTransitionRequest,
  PropertyInspectionCreateRequest,
  PropertyInspectionUpdateRequest,
  PropertyInspectionProjection,
  PropertyInspectionListProjection,
  PropertyNcrCreateRequest,
  PropertyNcrUpdateRequest,
  PropertyNcrProjection,
  PropertyNcrListProjection,
  PropertyNcrTransitionRequest,
  PropertySafetyIncidentCreateRequest,
  PropertySafetyIncidentUpdateRequest,
  PropertySafetyIncidentProjection,
  PropertySafetyIncidentListProjection,
  PropertySafetyIncidentTransitionRequest,
  PropertyChangeOrderCreateRequest,
  PropertyChangeOrderUpdateRequest,
  PropertyChangeOrderProjection,
  PropertyChangeOrderListProjection,
  PropertyChangeOrderTransitionRequest,
  PropertyPaymentCertificateCreateRequest,
  PropertyPaymentCertificateUpdateRequest,
  PropertyPaymentCertificateProjection,
  PropertyPaymentCertificateListProjection,
  PropertyPaymentCertificateTransitionRequest,
  PropertyHandoverCreateRequest,
  PropertyHandoverUpdateRequest,
  PropertyHandoverProjection,
  PropertyHandoverListProjection,
  PropertyHandoverTransitionRequest,
  PropertyLandRecordCreateRequest,
  PropertyLandRecordUpdateRequest,
  PropertyLandRecordProjection,
  PropertyLandRecordListProjection,
  PropertyLandRecordTransitionRequest,
  PropertyOverview
} from "@/lib/contracts";

export const propertyApi = {
  overview(signal?: AbortSignal) { return authenticatedApiRequest<PropertyOverview>("/api/v1/property/overview", { signal }); },
  property_units: recordApi<PropertyUnitCreateRequest, PropertyUnitUpdateRequest, PropertyUnitProjection, PropertyUnitListProjection, PropertyUnitTransitionRequest>("/api/v1/property/property-units"),
  project_milestones: recordApi<PropertyMilestoneCreateRequest, PropertyMilestoneUpdateRequest, PropertyMilestoneProjection, PropertyMilestoneListProjection, PropertyMilestoneTransitionRequest>("/api/v1/property/project-milestones"),
  construction_packages: recordApi<PropertyConstructionPackageCreateRequest, PropertyConstructionPackageUpdateRequest, PropertyConstructionPackageProjection, PropertyConstructionPackageListProjection, PropertyConstructionPackageTransitionRequest>("/api/v1/property/construction-packages"),
  construction_updates: recordApi<PropertyConstructionUpdateCreateRequest, PropertyConstructionUpdateUpdateRequest, PropertyConstructionUpdateProjection, PropertyConstructionUpdateListProjection, PropertyConstructionUpdateTransitionRequest>("/api/v1/property/construction-updates"),
  quality_inspections: recordApi<PropertyInspectionCreateRequest, PropertyInspectionUpdateRequest, PropertyInspectionProjection, PropertyInspectionListProjection, object>("/api/v1/property/quality-inspections"),
  quality_ncrs: recordApi<PropertyNcrCreateRequest, PropertyNcrUpdateRequest, PropertyNcrProjection, PropertyNcrListProjection, PropertyNcrTransitionRequest>("/api/v1/property/quality-ncrs"),
  safety_incidents: recordApi<PropertySafetyIncidentCreateRequest, PropertySafetyIncidentUpdateRequest, PropertySafetyIncidentProjection, PropertySafetyIncidentListProjection, PropertySafetyIncidentTransitionRequest>("/api/v1/property/safety-incidents"),
  change_orders: recordApi<PropertyChangeOrderCreateRequest, PropertyChangeOrderUpdateRequest, PropertyChangeOrderProjection, PropertyChangeOrderListProjection, PropertyChangeOrderTransitionRequest>("/api/v1/property/change-orders"),
  payment_certificates: recordApi<PropertyPaymentCertificateCreateRequest, PropertyPaymentCertificateUpdateRequest, PropertyPaymentCertificateProjection, PropertyPaymentCertificateListProjection, PropertyPaymentCertificateTransitionRequest>("/api/v1/property/payment-certificates"),
  project_handovers: recordApi<PropertyHandoverCreateRequest, PropertyHandoverUpdateRequest, PropertyHandoverProjection, PropertyHandoverListProjection, PropertyHandoverTransitionRequest>("/api/v1/property/project-handovers"),
  land_pipeline: recordApi<PropertyLandRecordCreateRequest, PropertyLandRecordUpdateRequest, PropertyLandRecordProjection, PropertyLandRecordListProjection, PropertyLandRecordTransitionRequest>("/api/v1/property/land-pipeline"),
};
