import { authenticatedApiRequest } from "@/lib/api";
import { recordApi } from "@/features/business-records/record-api";
import type {
  ItSystemCreateRequest,
  ItSystemUpdateRequest,
  ItSystemProjection,
  ItSystemListProjection,
  ItSystemTransitionRequest,
  ItIntegrationCreateRequest,
  ItIntegrationUpdateRequest,
  ItIntegrationProjection,
  ItIntegrationListProjection,
  ItIntegrationTransitionRequest,
  ItDatabaseCreateRequest,
  ItDatabaseUpdateRequest,
  ItDatabaseProjection,
  ItDatabaseListProjection,
  ItDatabaseTransitionRequest,
  ItEnvironmentCreateRequest,
  ItEnvironmentUpdateRequest,
  ItEnvironmentProjection,
  ItEnvironmentListProjection,
  ItEnvironmentTransitionRequest,
  ItRepositoryCreateRequest,
  ItRepositoryUpdateRequest,
  ItRepositoryProjection,
  ItRepositoryListProjection,
  ItRepositoryTransitionRequest,
  ItCicdPipelineCreateRequest,
  ItCicdPipelineUpdateRequest,
  ItCicdPipelineProjection,
  ItCicdPipelineListProjection,
  ItCicdPipelineTransitionRequest,
  ItCiRunCreateRequest,
  ItCiRunProjection,
  ItCiRunListProjection,
  ItReleaseCreateRequest,
  ItReleaseUpdateRequest,
  ItReleaseProjection,
  ItReleaseListProjection,
  ItReleaseTransitionRequest,
  ItTechnicalDebtCreateRequest,
  ItTechnicalDebtUpdateRequest,
  ItTechnicalDebtProjection,
  ItTechnicalDebtListProjection,
  ItTechnicalDebtTransitionRequest,
  ItServiceMonitorCreateRequest,
  ItServiceMonitorProjection,
  ItServiceMonitorListProjection,
  ItIncidentCreateRequest,
  ItIncidentUpdateRequest,
  ItIncidentProjection,
  ItIncidentListProjection,
  ItIncidentTransitionRequest,
  ItSecurityFindingCreateRequest,
  ItSecurityFindingUpdateRequest,
  ItSecurityFindingProjection,
  ItSecurityFindingListProjection,
  ItSecurityFindingTransitionRequest,
  ItBackupPolicyCreateRequest,
  ItBackupPolicyUpdateRequest,
  ItBackupPolicyProjection,
  ItBackupPolicyListProjection,
  ItBackupPolicyTransitionRequest,
  ItBackupRunCreateRequest,
  ItBackupRunProjection,
  ItBackupRunListProjection,
  ItRestoreTestCreateRequest,
  ItRestoreTestProjection,
  ItRestoreTestListProjection,
  ItDrPlanCreateRequest,
  ItDrPlanUpdateRequest,
  ItDrPlanProjection,
  ItDrPlanListProjection,
  ItDrPlanTransitionRequest,
  ItOverview
} from "@/lib/contracts";

export const itApi = {
  overview(signal?: AbortSignal) { return authenticatedApiRequest<ItOverview>("/api/v1/it/overview", { signal }); },
  systems: recordApi<ItSystemCreateRequest, ItSystemUpdateRequest, ItSystemProjection, ItSystemListProjection, ItSystemTransitionRequest>("/api/v1/it/systems"),
  integrations: recordApi<ItIntegrationCreateRequest, ItIntegrationUpdateRequest, ItIntegrationProjection, ItIntegrationListProjection, ItIntegrationTransitionRequest>("/api/v1/it/integrations"),
  databases: recordApi<ItDatabaseCreateRequest, ItDatabaseUpdateRequest, ItDatabaseProjection, ItDatabaseListProjection, ItDatabaseTransitionRequest>("/api/v1/it/databases"),
  environments: recordApi<ItEnvironmentCreateRequest, ItEnvironmentUpdateRequest, ItEnvironmentProjection, ItEnvironmentListProjection, ItEnvironmentTransitionRequest>("/api/v1/it/environments"),
  repositories: recordApi<ItRepositoryCreateRequest, ItRepositoryUpdateRequest, ItRepositoryProjection, ItRepositoryListProjection, ItRepositoryTransitionRequest>("/api/v1/it/repositories"),
  cicd_pipelines: recordApi<ItCicdPipelineCreateRequest, ItCicdPipelineUpdateRequest, ItCicdPipelineProjection, ItCicdPipelineListProjection, ItCicdPipelineTransitionRequest>("/api/v1/it/cicd-pipelines"),
  ci_runs: recordApi<ItCiRunCreateRequest, object, ItCiRunProjection, ItCiRunListProjection, object>("/api/v1/it/ci-runs"),
  releases: recordApi<ItReleaseCreateRequest, ItReleaseUpdateRequest, ItReleaseProjection, ItReleaseListProjection, ItReleaseTransitionRequest>("/api/v1/it/releases"),
  technical_debts: recordApi<ItTechnicalDebtCreateRequest, ItTechnicalDebtUpdateRequest, ItTechnicalDebtProjection, ItTechnicalDebtListProjection, ItTechnicalDebtTransitionRequest>("/api/v1/it/technical-debts"),
  service_monitors: recordApi<ItServiceMonitorCreateRequest, object, ItServiceMonitorProjection, ItServiceMonitorListProjection, object>("/api/v1/it/service-monitors"),
  incidents: recordApi<ItIncidentCreateRequest, ItIncidentUpdateRequest, ItIncidentProjection, ItIncidentListProjection, ItIncidentTransitionRequest>("/api/v1/it/incidents"),
  security_findings: recordApi<ItSecurityFindingCreateRequest, ItSecurityFindingUpdateRequest, ItSecurityFindingProjection, ItSecurityFindingListProjection, ItSecurityFindingTransitionRequest>("/api/v1/it/security-findings"),
  backup_policies: recordApi<ItBackupPolicyCreateRequest, ItBackupPolicyUpdateRequest, ItBackupPolicyProjection, ItBackupPolicyListProjection, ItBackupPolicyTransitionRequest>("/api/v1/it/backup-policies"),
  backup_runs: recordApi<ItBackupRunCreateRequest, object, ItBackupRunProjection, ItBackupRunListProjection, object>("/api/v1/it/backup-runs"),
  restore_tests: recordApi<ItRestoreTestCreateRequest, object, ItRestoreTestProjection, ItRestoreTestListProjection, object>("/api/v1/it/restore-tests"),
  dr_plans: recordApi<ItDrPlanCreateRequest, ItDrPlanUpdateRequest, ItDrPlanProjection, ItDrPlanListProjection, ItDrPlanTransitionRequest>("/api/v1/it/dr-plans"),
};
